### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by foxxxx001** [bentoml/OpenLLM#104]
When I run "bentoml serve svc.py:svc.I -p 2000" 
I  got such error
"2023-07-04T17:56:21+0800 [INFO] [cli] Starting production HTTP BentoServer from "svc.py:svc" listening on http://0.0.0.0:2000 (Press CTRL+C to quit)
2023-07-04T17:56:23+0800 [ERROR] [runner:pt-glm6b2p:1] An exception occurred while instantiating runner 'pt-glm6b2p', see details below:
2023-07-04T17:56:23+0800 [ERROR] [runner:pt-glm6b2p:1] Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/bentoml/_internal/utils/lazy_loader.py", line 69, in __getattr__
    self._module = self._load()
                   ^^^^^^^^^^^^
  File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/bentoml/_internal/utils/lazy_loader.py", line 53, in _load
    raise self._exc(f"{self._exc_msg} (reason: {err})") from None
bentoml.exceptions.MissingDependencyException: None (reason: No module named 'tensorflow')

**Comment by foxxxx001** [comment]
maybe special model
