### ISSUE TITLE
bug: `[ERROR] [runner:llm-falcon-runner:2] Exception in ASGI application`

### ISSUE THREAD

**Issue by eschmidbauer** [bentoml/OpenLLM#108]
### Describe the bug

[ERROR] [runner:llm-falcon-runner:2] Exception occurs when trying to perform inference on server.

### To reproduce

1. `openllm start falcon --model-id tiiuae/falcon-7b-instruct`
2. `export OPENLLM_ENDPOINT=http://localhost:3000 ; openllm query 'Explain to me the difference between "further" and "farther"'`

### Logs

```shell
> openllm start falcon --model-id tiiuae/falcon-7b-instruct

2023-07-07T16:43:35+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service.py:svc" can be accessed at http://localhost:3000/metrics.
2023-07-07T16:43:36+0000 [ERROR] [cli] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x7fb07859ba60>>
Traceback (most recent call last):
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/tornado/ioloop.py", line 919, in _run
    val = self.callback()
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/circus/util.py", line 1038, in wrapper
    raise ConflictError("arbiter is already running %s command"
circus.exc.ConflictError: arbiter is already running arbiter_start_watchers command
2023-07-07T16:43:37+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service.py:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.51s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.35s/it]

2023-07-07T16:44:05+0000 [INFO] [runner:llm-falcon-runner:1] _ (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 0.580ms (trace=2605c8e30c35548bc4d90c3c957ac0d3,span=654aaabd34034c93,sampled=1,service.name=llm-falcon-runner)
2023-07-07T16:44:05+0000 [INFO] [api_server:llm-falcon-service:60] 127.0.0.1:42138 (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 74.788ms (trace=2605c8e30c35548bc4d90c3c957ac0d3,span=4cfae1e62f99c4d2,sampled=1,service.name=llm-falcon-service)
2023-07-07T16:44:05+0000 [INFO] [runner:llm-falcon-runner:1] _ (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 0.383ms (trace=c65bad1b745313e5efd6d7d466f0be9b,span=74f1ac14fed1f1c0,sampled=1,service.name=llm-falcon-runner)
2023-07-07T16:44:05+0000 [INFO] [api_server:llm-falcon-service:59] 127.0.0.1:42152 (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 55.466ms (trace=c65bad1b745313e5efd6d7d466f0be9b,span=f8836bb604802243,sampled=1,service.name=llm-falcon-service)
2023-07-07T16:44:05+0000 [INFO] [api_server:llm-falcon-service:60] 127.0.0.1:42156 (scheme=http,method=GET,path=/docs.json,type=,length=) (status=200,type=application/json,length=8153) 9.468ms (trace=a4907d6361e4099a90d2d9b999854e9e,span=a6c9fb5e65baae5a,sampled=1,service.name=llm-falcon-service)
2023-07-07T16:44:05+0000 [INFO] [api_server:llm-falcon-service:60] 127.0.0.1:42168 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=714) 6.397ms (trace=ec1e23767fccad390d11ecfa97db8544,span=3dd320cbcef0156f,sampled=1,service.name=llm-falcon-service)
2023-07-07T16:44:05+0000 [INFO] [api_server:llm-falcon-service:62] 127.0.0.1:42170 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=714) 6.538ms (trace=b65bb86c166d27a93c6e9af46b991b44,span=f37146eaf7178e69,sampled=1,service.name=llm-falcon-service)
2023-07-07T16:44:07+0000 [ERROR] [runner:llm-falcon-runner:2] Exception in ASGI application
Traceback (most recent call last):
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/http/traffic.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 579, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/http/instruments.py", line 252, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/http/access.py", line 126, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 57, in wrapped_app
    raise exc
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 46, in wrapped_app
    await app(scope, receive, sender)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/routing.py", line 727, in __call__
    await route.handle(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/routing.py", line 285, in handle
    await self.app(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 57, in wrapped_app
    raise exc
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 46, in wrapped_app
    await app(scope, receive, sender)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    response = await func(request)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/runner_app.py", line 272, in _request_handler
    payload = await infer(params)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/marshal/dispatcher.py", line 182, in _func
    raise r
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/marshal/dispatcher.py", line 383, in outbound_call
    outputs = await self.callback(
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/runner_app.py", line 251, in infer_single
    ret = await runner_method.async_run(*params.args, **params.kwargs)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 59, in async_run_method
    return await anyio.to_thread.run_sync(
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runnable.py", line 140, in method
    return self.func(obj, *args, **kwargs)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/_llm.py", line 1207, in generate
    return self.generate(prompt, **attrs)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/models/falcon/modeling_falcon.py", line 102, in generate
    eos_token_id = attrs.pop("eos_token_id", self.tokenizer.eos_token_id)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/_llm.py", line 941, in tokenizer
    self.__llm_tokenizer__ = t.cast(_T, openllm.serialisation.load_tokenizer(self))
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 94, in load_tokenizer
    return openllm.transformers.load_tokenizer(llm)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/serialisation/transformers.py", line 239, in load_tokenizer
    tokenizer = llm.load_tokenizer(llm.tag, **tokenizer_attrs)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/models/falcon/modeling_falcon.py", line 56, in load_tokenizer
    return transformers.AutoTokenizer.from_pretrained(
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 719, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.tiiuae.falcon-7b-instruct.c7f670a03d987254220f343c6b026ea0c5147185.configuration_RW.RWConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.
2023-07-07T16:44:07+0000 [ERROR] [api_server:llm-falcon-service:63] Exception on /v1/generate [POST] (trace=328421a74eec6856b8575ff33d6ded1f,span=f878adce871577e0,sampled=1,service.name=llm-falcon-service)
Traceback (most recent call last):
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/http_app.py", line 341, in api_func
    output = await api.func(*args)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/_service.py", line 90, in generate_v1
    responses = await runner.generate.async_run(qa_inputs.prompt, **config)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 242, in async_run_method
    raise RemoteException(
bentoml.exceptions.RemoteException: An unexpected exception occurred in remote runner llm-falcon-runner: [500] Internal Server Error
2023-07-07T16:44:07+0000 [INFO] [api_server:llm-falcon-service:63] 127.0.0.1:42186 (scheme=http,method=POST,path=/v1/generate,type=application/json,length=7113) (status=500,type=application/json,length=2) 181.435ms (trace=328421a74eec6856b8575ff33d6ded1f,span=f878adce871577e0,sampled=1,service.name=llm-falcon-service)
```

### Environment

> bentoml env
#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.0.23
`python`: 3.10.12
`platform`: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
`uid_gid`: 1004:1004
`conda`: 23.3.1
`in_conda_env`: True
<details><summary><code>conda_packages</code></summary>

<br>

```yaml
name: openllm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.1.2=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.20.3
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.7.1
      - appdirs==1.4.4
      - asgiref==3.7.2
      - async-timeout==4.0.2
      - attrs==23.1.0
      - bentoml==1.0.23
      - build==0.10.0
      - cattrs==23.1.2
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - circus==0.18.0
      - click==8.1.4
      - click-option-group==0.5.6
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - datasets==2.13.1
      - deepmerge==1.1.0
      - deprecated==1.2.14
      - dill==0.3.6
      - einops==0.6.1
      - exceptiongroup==1.1.2
      - filelock==3.12.2
      - filetype==1.2.0
      - frozenlist==1.3.3
      - fs==2.4.16
      - fsspec==2023.6.0
      - grpcio==1.56.0
      - grpcio-health-checking==1.48.2
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - idna==3.4
      - importlib-metadata==6.0.1
      - inflection==0.5.1
      - jinja2==3.1.2
      - lit==16.0.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.25.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openllm==0.1.20
      - opentelemetry-api==1.17.0
      - opentelemetry-instrumentation==0.38b0
      - opentelemetry-instrumentation-aiohttp-client==0.38b0
      - opentelemetry-instrumentation-asgi==0.38b0
      - opentelemetry-instrumentation-grpc==0.38b0
      - opentelemetry-sdk==1.17.0
      - opentelemetry-semantic-conventions==0.38b0
      - opentelemetry-util-http==0.38b0
      - optimum==1.9.0
      - orjson==3.9.2
      - packaging==23.1
      - pandas==2.0.3
      - pathspec==0.11.1
      - pillow==10.0.0
      - pip-requirements-parser==32.0.1
      - pip-tools==6.14.0
      - prometheus-client==0.17.0
      - protobuf==3.20.3
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pydantic==1.10.11
      - pygments==2.15.1
      - pynvml==11.5.0
      - pyparsing==3.1.0
      - pyproject-hooks==1.0.0
      - pyre-extensions==0.0.29
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.1.0
      - regex==2023.6.3
      - requests==2.31.0
      - rich==13.4.2
      - safetensors==0.3.1
      - schema==0.7.5
      - sentencepiece==0.1.99
      - simple-di==0.1.5
      - six==1.16.0
      - sniffio==1.3.0
      - starlette==0.28.0
      - sympy==1.12
      - tabulate==0.9.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.0.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - transformers==4.30.2
      - triton==2.0.0
      - typing-extensions==4.7.1
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - urllib3==2.0.3
      - uvicorn==0.22.0
      - watchfiles==0.19.0
      - wcwidth==0.2.6
      - wrapt==1.15.0
      - xformers==0.0.20
      - xxhash==3.2.0
      - yarl==1.9.2
      - zipp==3.15.0
prefix: /miniconda3/envs/openllm
```

</details>

<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.20.3
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.2
attrs==23.1.0
bentoml==1.0.23
build==0.10.0
cattrs==23.1.2
certifi==2023.5.7
charset-normalizer==3.1.0
circus==0.18.0
click==8.1.4
click-option-group==0.5.6
cloudpickle==2.2.1
cmake==3.26.4
coloredlogs==15.0.1
contextlib2==21.6.0
datasets==2.13.1
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.6
docutils==0.16
einops==0.6.1
exceptiongroup==1.1.2
filelock==3.12.2
filetype==1.2.0
frozenlist==1.3.3
fs==2.4.16
fsspec==2023.6.0
grpcio==1.56.0
grpcio-health-checking==1.48.2
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
humanfriendly==10.0
idna==3.4
importlib-metadata==6.0.1
inflection==0.5.1
Jinja2==3.1.2
lit==16.0.6
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
networkx==3.1
numpy==1.25.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
openllm==0.1.20
opentelemetry-api==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-aiohttp-client==0.38b0
opentelemetry-instrumentation-asgi==0.38b0
opentelemetry-instrumentation-grpc==0.38b0
opentelemetry-sdk==1.17.0
opentelemetry-semantic-conventions==0.38b0
opentelemetry-util-http==0.38b0
optimum==1.9.0
orjson==3.9.2
packaging==23.1
pandas==2.0.3
pathspec==0.11.1
Pillow==10.0.0
pip-requirements-parser==32.0.1
pip-tools==6.14.0
prometheus-client==0.17.0
protobuf==3.20.3
psutil==5.9.5
pyarrow==12.0.1
pydantic==1.10.11
Pygments==2.15.1
pynvml==11.5.0
pyparsing==3.1.0
pyproject_hooks==1.0.0
pyre-extensions==0.0.29
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3
PyYAML==6.0
pyzmq==25.1.0
regex==2023.6.3
requests==2.31.0
rich==13.4.2
rsa==4.7.2
safetensors==0.3.1
schema==0.7.5
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.28.0
sympy==1.12
tabulate==0.9.0
tokenizers==0.13.3
tomli==2.0.1
torch==2.0.1
tornado==6.3.2
tqdm==4.65.0
transformers==4.30.2
triton==2.0.0
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.3
uvicorn==0.22.0
watchfiles==0.19.0
wcwidth==0.2.6
wrapt==1.15.0
xformers==0.0.20
xxhash==3.2.0
yarl==1.9.2
zipp==3.15.0
```

</details>

### System information (Optional)

ubuntu 22
2x nvidia a100 (Driver Version: 535.54.03    CUDA Version: 12.2)

**Comment by wey-gu** [comment]
I am encountering the same error 😭:

```
$ openllm start chatglm --model-id thudm/chatglm2-6b

...

2023-07-18T11:57:27+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service.py:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
Loading /home/w/bentoml/models/pt-thudm-chatglm2-6b/4e38bef4c028beafc8fb1837462f74c02e68fcc2 requires to execute some code in that repo, you can inspect the content of the repository at https://hf.co//home/w/bentoml/models/pt-thudm-chatglm2-6b/4e38bef4c028beafc8fb1837462f74c02e68fcc2. You can dismiss this prompt by passing `trust_remote_code=True`.
Do you accept? [y/N] 2023-07-18T11:57:38+0000 [ERROR] [runner:llm-chatglm-runner:1] An exception occurred while instantiating runner 'llm-chatglm-runner', see details below:
2023-07-18T11:57:38+0000 [ERROR] [runner:llm-chatglm-runner:1] Traceback (most recent call last):
  File "/home/w/.local/lib/python3.8/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
    self._set_handle(LocalRunnerRef)
  File "/home/w/.local/lib/python3.8/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
    runner_handle = handle_class(self, *args, **kwargs)
  File "/home/w/.local/lib/python3.8/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
    self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
  File "/home/w/.local/lib/python3.8/site-packages/openllm/_llm.py", line 1162, in __init__
    __self.model = self.model  # keep a loaded reference
  File "/home/w/.local/lib/python3.8/site-packages/openllm/_llm.py", line 933, in model
    _M, openllm.serialisation.load_model(self, *self._model_decls, **self._model_attrs)
  File "/home/w/.local/lib/python3.8/site-packages/openllm/serialisation/__init__.py", line 85, in load_model
    return openllm.transformers.load_model(llm, *decls, **attrs)
  File "/home/w/.local/lib/python3.8/site-packages/openllm/serialisation/transformers.py", line 220, in load_model
    model = infer_autoclass_from_llm_config(llm, config).from_pretrained(
  File "/home/w/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 470, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/w/.local/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 538, in resolve_trust_remote_code
    answer = input(
EOFError: EOF when reading a line
```

**Comment by aarnphm** [comment]
What version of openllm is this?

Maybe you can do a `openllm prune -y`, `pip install -U openllm --force-reinstall`?

Good to also try within a virtualenv
