### ISSUE TITLE
bug: "Timeout doesn't fit into C timeval" in async context

### ISSUE THREAD

**Issue by MarcelSoftware** [bentoml/OpenLLM#111]
### Describe the bug

Since commit 528f76e1d071fa576d8654b624b63b60c5964252 there is an if statement ```if(in_async_context())``` in openllm_client/runtimes/base.py
If this is true, and the httpx post is executed I get "OverflowError: timeout doesn't fit into C timeval"

The timeout value I can see in my debugger is 36000000. When I set the timeout value (in the debugger) to 1000, the exception is not thrown and I get a correct result.

### To reproduce

Start LLMChain::run in an async context

```python
import asyncio
from langchain import PromptTemplate, LLMChain
from langchain.llms import OpenLLM

async def foo():
    server_url = "http://hostname:port"
    temp = 0.2
    llm = OpenLLM(server_url=server_url, temperature=temp)

    print("llm type: " + str(type(llm)))

    template = "What is a good name for a company that makes {product} at this place: {place}?"
    prompt = PromptTemplate(template=template, input_variables=["product", "place"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)

    generated = llm_chain.run(product="mechanical keyboard", place="Detroit")
    print(generated)


loop = asyncio.get_event_loop()
loop.run_until_complete(foo())
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\nicegui\page.py", line 87, in decorated
    result = func(*dec_args, **dec_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\src\router_test.py", line 22, in do_stuff
    generated = stuff()
                ^^^^^^^
  File "C:\svn\ocean\AI_Assistant\src\router_test.py", line 15, in stuff
    generated = llm_chain.run(product="mechanical keyboard", place="Detroit")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\base.py", line 445, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\base.py", line 243, in __call__
    raise e
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 186, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 279, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 223, in _generate_helper
    raise e
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 210, in _generate_helper
    self._generate(
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 602, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\openllm.py", line 270, in _call
    return self._client.query(prompt, **config.model_dump(flatten=True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\openllm_client\runtimes\base.py", line 184, in query
    result = httpx.post(
             ^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_api.py", line 304, in post
    return request(
           ^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 261, in handle_request
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection.py", line 92, in handle_request
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection.py", line 69, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection.py", line 117, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\backends\sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\socket.py", line 833, in create_connection
    sock.settimeout(timeout)
OverflowError: timeout doesn't fit into C timeval
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\fastapi\routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\nicegui\page.py", line 87, in decorated
    result = func(*dec_args, **dec_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\src\router_test.py", line 22, in do_stuff
    generated = stuff()
                ^^^^^^^
  File "C:\svn\ocean\AI_Assistant\src\router_test.py", line 15, in stuff
    generated = llm_chain.run(product="mechanical keyboard", place="Detroit")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\base.py", line 445, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\base.py", line 243, in __call__
    raise e
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 186, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 279, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 223, in _generate_helper
    raise e
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 210, in _generate_helper
    self._generate(
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\base.py", line 602, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\langchain\llms\openllm.py", line 270, in _call
    return self._client.query(prompt, **config.model_dump(flatten=True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\openllm_client\runtimes\base.py", line 184, in query
    result = httpx.post(
             ^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_api.py", line 304, in post
    return request(
           ^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 261, in handle_request
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection.py", line 92, in handle_request
    raise exc
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection.py", line 69, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\_sync\connection.py", line 117, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\svn\ocean\AI_Assistant\env\Lib\site-packages\httpcore\backends\sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\socket.py", line 833, in create_connection
    sock.settimeout(timeout)
OverflowError: timeout doesn't fit into C timeval
```

### Environment

(env) PS C:\svn\ocean\AI_Assistant> bentoml env
#### Environment variable    
                             
```bash                      
BENTOML_DEBUG=''             
BENTOML_QUIET=''             
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''      
BENTOML_CONFIG=''            
BENTOML_CONFIG_OPTIONS=''    
BENTOML_PORT=''              
BENTOML_HOST=''              
BENTOML_API_WORKERS=''       
```                          
                             
#### System information      

`bentoml`: 1.0.23
`python`: 3.11.3
`platform`: Windows-10-10.0.19045-SP0
`is_window_admin`: True
<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.20.3
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.7.0
appdirs==1.4.4
argilla==0.0.1
asgiref==3.7.2
async-timeout==4.0.2
attrs==23.1.0
beautifulsoup4==4.12.2
bentoml==1.0.23
bidict==0.22.1
blinker==1.6.2
bottle==0.12.25
bs4==0.0.1
build==0.10.0
cattrs==23.1.2
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
circus==0.18.0
click==8.1.3
click-option-group==0.5.6
cloudpickle==2.2.1
clr-loader==0.2.5
colorama==0.4.6
colorclass==2.2.2
coloredlogs==15.0.1
compressed-rtf==1.0.6
contextlib2==21.6.0
contourpy==1.1.0
cryptography==41.0.1
cycler==0.11.0
dataclasses-json==0.5.9
datasets==2.13.1
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.6
diskcache==5.6.1
easygui==0.98.3
ebcdic==1.1.1
et-xmlfile==1.1.0
extract-msg==0.41.5
fastapi==0.99.1
fastapi-socketio==0.0.10
filelock==3.12.2
filetype==1.2.0
Flask==2.3.2
fonttools==4.40.0
frozenlist==1.3.3
fs==2.4.16
fsspec==2023.6.0
gpt4all==1.0.1
greenlet==2.0.2
grpcio==1.56.0
grpcio-health-checking==1.48.2
grpcio-tools==1.56.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.17.2
httptools==0.5.0
httpx==0.24.1
huggingface-hub==0.15.1
humanfriendly==10.0
hyperframe==6.0.1
idna==3.4
IMAPClient==2.3.1
importlib-metadata==6.0.1
inflection==0.5.1
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.3.1
jsonify==0.5
kiwisolver==1.4.4
langchain==0.0.229
langchainplus-sdk==0.0.20
lark-parser==0.12.0
llama-cpp-python==0.1.67
lxml==4.9.2
Markdown==3.4.3
markdown-it-py==3.0.0
markdown2==2.4.9
MarkupSafe==2.1.3
marshmallow==3.19.0
marshmallow-enum==1.5.1
matplotlib==3.7.1
mdurl==0.1.2
mpmath==1.3.0
msg-parser==1.2.0
msoffcrypto-tool==5.0.1
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
networkx==3.1
nicegui==1.2.24
nltk==3.8.1
numexpr==2.8.4
numpy==1.25.0
olefile==0.46
oletools==0.60.1
openapi-schema-pydantic==1.2.4
openllm==0.1.19
openpyxl==3.1.2
opentelemetry-api==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-aiohttp-client==0.38b0
opentelemetry-instrumentation-asgi==0.38b0
opentelemetry-instrumentation-grpc==0.38b0
opentelemetry-sdk==1.17.0
opentelemetry-semantic-conventions==0.38b0
opentelemetry-util-http==0.38b0
optimum==1.1.1
orjson==3.9.1
packaging==23.1
pandas==2.0.3
pathspec==0.11.1
pcodedmp==1.2.6
pdf2image==1.16.3
pdfminer.six==20221105
Pillow==10.0.0
pip-requirements-parser==32.0.1
pip-tools==6.14.0
plotly==5.15.0
portalocker==2.7.0
prometheus-client==0.17.0
prompt-toolkit==3.0.38
protobuf==4.23.3
proxy-tools==0.1.0
pscript==0.7.7
psutil==5.9.5
pyarrow==12.0.1
pycparser==2.21
pydantic==1.10.10
Pygments==2.15.1
pynvml==11.5.0
pypandoc==1.11
pyparsing==2.4.7
pyproject_hooks==1.0.0
pyreadline3==3.4.1
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==1.0.0
python-engineio==4.4.1
python-json-logger==2.0.7
python-magic==0.4.27
python-multipart==0.0.6
python-pptx==0.6.21
python-socketio==5.8.0
pythonnet==3.0.1
pytz==2023.3
pywebview==4.2.2
pywin32==306
PyYAML==6.0
pyzmq==25.1.0
qdrant-client==1.3.1
ReallySimpleDB==1.2
red-black-tree-mod==1.20
regex==2023.6.3
requests==2.31.0
rich==13.4.2
RTFDE==0.0.2
safetensors==0.3.1
schema==0.7.5
scikit-learn==1.3.0
scipy==1.11.1
sentence-transformers==2.2.2
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
SQLAlchemy==2.0.17
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tenacity==8.2.2
threadpoolctl==3.1.0
tiktoken==0.4.0
tokenizers==0.13.3
torch==2.0.1
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
transformers==4.30.2
typing-inspect==0.9.0
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==5.0.1
unstructured==0.7.12
urllib3==1.26.16
uvicorn==0.20.0
vbuild==0.8.1
wcwidth==0.2.6
websockets==11.0.3
Werkzeug==2.3.6
win-unicode-console==0.5
wrapt==1.15.0
xlrd==2.0.1
XlsxWriter==3.1.2
xxhash==3.2.0
yarl==1.9.2
zipp==3.15.0
```

</details>

(env) PS C:\svn\ocean\AI_Assistant> transformers-cli env

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.30.2
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.11.3
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by aarnphm** [comment]
Hey there, you are running a sync function within async context. This is not recommended.

The reason for https://github.com/bentoml/OpenLLM/commit/528f76e1d071fa576d8654b624b63b60c5964252 is to use httpx within an async call. This assumes that all function within this context are async function.

`llm.run` is a sync call, which is blocking. Please use the async variant of Langchain `run`.

**Comment by aarnphm** [comment]
This is not a bug, but rather a usage issue.
