### ISSUE TITLE
bug: int8-quantized Llama-2 fails to generate

### ISSUE THREAD

**Issue by geoffreyangus** [bentoml/OpenLLM#196]
### Describe the bug

When I ping the endpoint started for an int8-quantized Llama-2, I get the following error: 

```
  File "/opt/conda/lib/python3.9/site-packages/openllm/models/llama/modeling_llama.py", line 36, in generate
    return self.tokenizer.batch_decode(self.model.generate(**self.tokenizer(prompt, return_tensors="pt").to(self.device), generation_config=self.config.model_construct_env(**attrs).to_generation_config(), do_sample=True, stopping_criteria=openllm.StoppingCriteriaList([openllm.StopOnTokens()])), skip_special_tokens=True, clean_up_tokenization_spaces=True)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/opt/conda/lib/python3.9/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

It seems like this has to do with a dtype mismatch.

### To reproduce

Steps to reproduce the bug:

1. Use docker image: `ghcr.io/bentoml/openllm:sha-2d47a54@sha256:13640cf2210ae60cf9eb44e81b673166519e53ac712a0fff92dfaf62ae835d43` on some machine with a GPU capable of fitting an int8 quantized Llama-2 model.
2. Run `pip install openllm==0.2.17`
3. in one terminal, run `openllm start llama --model-id meta-llama/Llama-2-7b-chat-hf --quantise int8 --device 0`
4. In another terminal, run `curl -X POST http://localhost:3000/v1/generate -H "Content-Type: application/json" -d '{"prompt": "What is the capital of Italy?"}' -v`

### Logs

```shell
$ openllm start llama --model-id meta-llama/Llama-2-7b-chat-hf --quantise int8 --device 0
'--quantize=int8' might not work with 'safetensors' serialisation format. Use with caution!. To silence this warning, set "OPENLLM_SERIALIZATION_WARNING=False"
Note: You can always fallback to '--serialisation legacy' when running quantisation.
2023-08-10T18:25:35+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service.py:svc" can be accessed at http://localhost:3000/metrics.
2023-08-10T18:25:36+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service.py:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
2023-08-10 18:25:43.093395: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.65s/it]
2023-08-10T18:26:58+0000 [ERROR] [cli:llm-llama-runner:1] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/http/traffic.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 580, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/http/instruments.py", line 252, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/http/access.py", line 126, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 57, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 46, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 727, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 285, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 57, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 46, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    response = await func(request)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/runner_app.py", line 273, in _request_handler
    payload = await infer(params)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/marshal/dispatcher.py", line 182, in _func
    raise r
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/marshal/dispatcher.py", line 377, in outbound_call
    outputs = await self.callback(
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/runner_app.py", line 253, in infer_single
    ret = await runner_method.async_run(*params.args, **params.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 59, in async_run_method
    return await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runnable.py", line 140, in method
    return self.func(obj, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 1125, in generate
    return self.generate(prompt, **attrs)
  File "/opt/conda/lib/python3.9/site-packages/openllm/models/llama/modeling_llama.py", line 36, in generate
    return self.tokenizer.batch_decode(self.model.generate(**self.tokenizer(prompt, return_tensors="pt").to(self.device), generation_config=self.config.model_construct_env(**attrs).to_generation_config(), do_sample=True, stopping_criteria=openllm.StoppingCriteriaList([openllm.StopOnTokens()])), skip_special_tokens=True, clean_up_tokenization_spaces=True)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/opt/conda/lib/python3.9/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
2023-08-10T18:26:58+0000 [ERROR] [cli:llm-llama-service:37] Exception on /v1/generate [POST] (trace=ae678274d9646a6422353c1641754fbf,span=1843178c1bf80050,sampled=1,service.name=llm-llama-service)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/http_app.py", line 341, in api_func
    output = await api.func(*args)
  File "/opt/conda/lib/python3.9/site-packages/openllm/_service.py", line 45, in generate_v1
    responses = await runner.generate.async_run(qa_inputs.prompt, **config)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 242, in async_run_method
    raise RemoteException(
bentoml.exceptions.RemoteException: An unexpected exception occurred in remote runner llm-llama-runner: [500] Internal Server Error
2023-08-10T18:26:58+0000 [INFO] [cli:llm-llama-service:37] 127.0.0.1:59510 (scheme=http,method=POST,path=/v1/generate,type=application/json,length=43) (status=500,type=application/json,length=2) 1211.996ms (trace=ae678274d9646a6422353c1641754fbf,span=1843178c1bf80050,sampled=1,service.name=llm-llama-service)
```

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.1
`python`: 3.9.16
`platform`: Linux-5.4.0-122-generic-x86_64-with-glibc2.35
`uid_gid`: 0:0
`conda`: 23.3.1
`in_conda_env`: True
<details><summary><code>conda_packages</code></summary>

<br>

```yaml
name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli-python=1.0.9=py39h5a03fae_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.3.1=py39hf3d152e_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.8.0=pyhd8ed1ab_0
  - cryptography=41.0.2=py39hd4f0224_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - filelock=3.12.2=pyhd8ed1ab_0
  - fmt=9.1.0=h924138e_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h376b7d2_1
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libarchive=3.6.2=h039dbb9_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcurl=7.88.1=hdc1c0ab_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - libhwloc=2.9.2=nocuda_h7313eea_1008
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libmamba=1.4.1=hcea66bb_0
  - libmambapy=1.4.1=py39hf0aba66_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.9.0.86=0
  - libsolv=0.7.24=hfc55251_1
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mamba=1.4.1=py39hc5d2bb1_0
  - markupsafe=2.1.3=py39hd1e30aa_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - networkx=3.1=pyhd8ed1ab_0
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pip=23.0.1=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py39hb9d737c_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=3_cp39
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rocm-smi=5.6.0=h59595ed_1
  - ruamel.yaml=0.17.32=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.7=py39h72bdee0_1
  - setuptools=65.6.3=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchtriton=2.0.0=py39
  - tqdm=4.65.0=pyhd8ed1ab_1
  - wheel=0.41.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml-cpp=0.7.0=h27087fc_2
  - zstandard=0.19.0=py39h6e5214e_2
  - zstd=1.5.2=hfc55251_7
  - pip:
      - absl-py==1.4.0
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - anyio==3.7.1
      - appdirs==1.4.4
      - asgiref==3.7.2
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - bentoml==1.1.1
      - bitsandbytes==0.41.1
      - build==0.10.0
      - cachetools==5.3.1
      - cattrs==23.1.2
      - chex==0.1.7
      - circus==0.18.0
      - click==8.1.6
      - click-option-group==0.5.6
      - cloudpickle==2.2.1
      - cmake==3.27.1
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - cpm-kernels==1.0.11
      - cuda-python==12.2.0
      - cython==3.0.0
      - datasets==2.14.3
      - deepmerge==1.1.0
      - deprecated==1.2.14
      - dill==0.3.7
      - dm-tree==0.1.8
      - einops==0.6.1
      - etils==1.4.1
      - exceptiongroup==1.1.2
      - fairscale==0.4.13
      - fastcore==1.5.29
      - filetype==1.2.0
      - flatbuffers==23.5.26
      - flax==0.7.1
      - frozenlist==1.4.0
      - fs==2.4.16
      - fsspec==2023.6.0
      - gast==0.4.0
      - ghapi==1.0.4
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.56.2
      - grpcio-health-checking==1.56.2
      - h11==0.14.0
      - h5py==3.9.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - importlib-metadata==6.0.1
      - importlib-resources==6.0.1
      - inflection==0.5.1
      - jax==0.4.14
      - jaxlib==0.4.14+cuda11.cudnn86
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - keras==2.13.1
      - libclang==16.0.6
      - lit==16.0.6
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - nest-asyncio==1.5.7
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - openllm==0.2.17
      - opentelemetry-api==1.18.0
      - opentelemetry-instrumentation==0.39b0
      - opentelemetry-instrumentation-aiohttp-client==0.39b0
      - opentelemetry-instrumentation-asgi==0.39b0
      - opentelemetry-instrumentation-grpc==0.39b0
      - opentelemetry-sdk==1.18.0
      - opentelemetry-semantic-conventions==0.39b0
      - opentelemetry-util-http==0.39b0
      - opt-einsum==3.3.0
      - optax==0.1.7
      - optimum==1.11.0
      - orbax-checkpoint==0.3.2
      - orjson==3.9.4
      - pandas==2.0.3
      - pathspec==0.11.2
      - peft==0.4.0
      - pillow==10.0.0
      - pip-requirements-parser==32.0.1
      - pip-tools==7.2.0
      - prometheus-client==0.17.1
      - protobuf==4.23.4
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.12
      - pygments==2.16.1
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyre-extensions==0.0.29
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - ray==2.6.0
      - referencing==0.30.2
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rpds-py==0.9.2
      - rsa==4.9
      - safetensors==0.3.2
      - schema==0.7.5
      - scipy==1.11.1
      - sentencepiece==0.1.99
      - simple-di==0.1.5
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - starlette==0.28.0
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorstore==0.1.40
      - termcolor==2.3.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.0.1
      - tornado==6.3.2
      - transformers==4.31.0
      - trl==0.5.0
      - typing-extensions==4.5.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - uvicorn==0.23.2
      - watchfiles==0.19.0
      - wcwidth==0.2.6
      - werkzeug==2.3.6
      - wrapt==1.15.0
      - xformers==0.0.20
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.16.2
prefix: /opt/conda
```

</details>

<details><summary><code>pip_packages</code></summary>

<br>

```
absl-py==1.4.0
accelerate==0.21.0
aiohttp==3.8.5
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
bentoml==1.1.1
bitsandbytes==0.41.1
boltons @ file:///home/conda/feedstock_root/build_artifacts/boltons_1677499911949/work
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1687884021435/work
build==0.10.0
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.7.22
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1671179360775/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1688813409104/work
chex==0.1.7
circus==0.18.0
click==8.1.6
click-option-group==0.5.6
cloudpickle==2.2.1
cmake==3.27.1
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
coloredlogs==15.0.1
conda==23.3.1
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1669907009957/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1685101166527/work
contextlib2==21.6.0
cpm-kernels==1.0.11
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1689055986092/work
cuda-python==12.2.0
Cython==3.0.0
datasets==2.14.3
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
dm-tree==0.1.8
einops==0.6.1
etils==1.4.1
exceptiongroup==1.1.2
fairscale==0.4.13
fastcore==1.5.29
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1686612785345/work
filetype==1.2.0
flatbuffers==23.5.26
flax==0.7.1
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.6.0
gast==0.4.0
ghapi==1.0.4
gitdb==4.0.10
GitPython==3.1.32
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808679441/work
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.56.2
grpcio-health-checking==1.56.2
h11==0.14.0
h5py==3.9.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
humanfriendly==10.0
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata==6.0.1
importlib-resources==6.0.1
inflection==0.5.1
jax==0.4.14
jaxlib==0.4.14+cuda11.cudnn86
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/work
jsonpointer==2.0
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
keras==2.13.1
libclang==16.0.6
libmambapy @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1680002410624/work/libmambapy
lit==16.0.6
mamba @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1680002410624/work/mamba
Markdown==3.4.4
markdown-it-py==3.0.0
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1685769048265/work
mdurl==0.1.2
ml-dtypes==0.2.0
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
msgpack==1.0.5
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
nest-asyncio==1.5.7
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1680692919326/work
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.2
openllm==0.2.17
opentelemetry-api==1.18.0
opentelemetry-instrumentation==0.39b0
opentelemetry-instrumentation-aiohttp-client==0.39b0
opentelemetry-instrumentation-asgi==0.39b0
opentelemetry-instrumentation-grpc==0.39b0
opentelemetry-sdk==1.18.0
opentelemetry-semantic-conventions==0.39b0
opentelemetry-util-http==0.39b0
opt-einsum==3.3.0
optax==0.1.7
optimum==1.11.0
orbax-checkpoint==0.3.2
orjson==3.9.4
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==2.0.3
pathspec==0.11.2
peft==0.4.0
Pillow==10.0.0
pip-requirements-parser==32.0.1
pip-tools==7.2.0
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1687776318736/work
prometheus-client==0.17.1
protobuf==4.23.4
psutil==5.9.5
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1666836642684/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic==1.10.12
Pygments==2.16.1
pynvml==11.5.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1685514481738/work
pyparsing==3.1.1
pyproject_hooks==1.0.0
pyre-extensions==0.0.29
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3
PyYAML==6.0.1
pyzmq==25.1.0
ray==2.6.0
referencing==0.30.2
regex==2023.6.3
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
requests-oauthlib==1.3.1
rich==13.5.2
rpds-py==0.9.2
rsa==4.9
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1686993888032/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1670412733608/work
safetensors==0.3.2
schema==0.7.5
scipy==1.11.1
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
starlette==0.28.0
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1684180540116/work
tabulate==0.9.0
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow==2.13.0
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.33.0
tensorstore==0.1.40
termcolor==2.3.0
tokenizers==0.13.3
tomli==2.0.1
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
torch==2.0.1
tornado==6.3.2
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
transformers==4.31.0
triton==2.0.0
trl==0.5.0
typing-inspect==0.9.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.16
uvicorn==0.23.2
watchfiles==0.19.0
wcwidth==0.2.6
Werkzeug==2.3.6
wrapt==1.15.0
xformers==0.0.20
xxhash==3.3.0
yarl==1.9.2
zipp==3.16.2
zstandard==0.19.0
```

</details>

### System information (Optional)

Platform: Ubuntu 22.04.2 LTS
GPU: NVIDIA RTX A5000 (2x)

**Comment by aarnphm** [comment]
Can you try again with the latest revision? Sorry for getting back to you so late.
