### ISSUE TITLE
bug: AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit' on GPTQ Inference

### ISSUE THREAD

**Issue by aliozts** [bentoml/OpenLLM#225]
### Describe the bug

I was trying to utilize `gptq` inference as in the examples in the homepage 

```
openllm start falcon --model-id TheBloke/falcon-40b-instruct-GPTQ --quantize gptq --device 0
```

It produced this error. My use-case was utilizing [LLama 2 70B GPTQ](https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ) model with `OpenLLM`. It produced the error below when I tried it. May I ask for help about this?

### To reproduce

```
pip install openllm
```

```
openllm start llama --model-id TheBloke/Llama-2-70B-chat-GPTQ --quantize gptq --device 0
```

### Logs

```shell
--quantize=gptq' might not work with 'safetensors' serialisation format. Use with caution!. To silence this warning, set "OPENLLM_SERIALIZATION_WARNING=False"
Note: You can always fallback to '--serialisation legacy' when running quantisation.
2023-08-16T11:28:33+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service:svc" can be accessed at http://localhost:3000/metrics.
2023-08-16T11:28:33+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
2023-08-16T11:28:41+0000 [ERROR] [runner:llm-llama-runner:1] An exception occurred while instantiating runner 'llm-llama-runner', see details below:
2023-08-16T11:28:41+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
 self._set_handle(LocalRunnerRef)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
 runner_handle = handle_class(self, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
 self._runnable = runner.runnable_class(**runner.runnable_init_params) # type: ignore
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
 if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
 model = self.load_model(*self._model_decls, **self._model_attrs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
 return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
 return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 156, in load_model
 model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
 return model_class.from_pretrained(
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2262, in from_pretrained
 load_in_8bit = quantization_config.load_in_8bit
AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit'

2023-08-16T11:28:41+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
 async with self.lifespan_context(app) as maybe_state:
 File "/opt/conda/envs/inference/lib/python3.10/contextlib.py", line 199, in __aenter__
 return await anext(self.gen)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
 on_startup()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 312, in init_local
 raise e
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
 self._set_handle(LocalRunnerRef)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
 runner_handle = handle_class(self, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
 self._runnable = runner.runnable_class(**runner.runnable_init_params) # type: ignore
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
 if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
 model = self.load_model(*self._model_decls, **self._model_attrs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
 return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
 return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 156, in load_model
 model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
 return model_class.from_pretrained(
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2262, in from_pretrained
 load_in_8bit = quantization_config.load_in_8bit
AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit'

2023-08-16T11:28:41+0000 [ERROR] [runner:llm-llama-runner:1] Application startup failed. Exiting.
2023-08-16T11:28:47+0000 [ERROR] [runner:llm-llama-runner:1] An exception occurred while instantiating runner 'llm-llama-runner', see details below:
2023-08-16T11:28:47+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
 self._set_handle(LocalRunnerRef)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
 runner_handle = handle_class(self, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
 self._runnable = runner.runnable_class(**runner.runnable_init_params) # type: ignore
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
 if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
 model = self.load_model(*self._model_decls, **self._model_attrs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
 return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
 return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 156, in load_model
 model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
 return model_class.from_pretrained(
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2262, in from_pretrained
 load_in_8bit = quantization_config.load_in_8bit
AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit'

2023-08-16T11:28:47+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
 async with self.lifespan_context(app) as maybe_state:
 File "/opt/conda/envs/inference/lib/python3.10/contextlib.py", line 199, in __aenter__
 return await anext(self.gen)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
 on_startup()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 312, in init_local
 raise e
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
 self._set_handle(LocalRunnerRef)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
 runner_handle = handle_class(self, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
 self._runnable = runner.runnable_class(**runner.runnable_init_params) # type: ignore
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
 if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
 model = self.load_model(*self._model_decls, **self._model_attrs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
 return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
 return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 156, in load_model
 model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
 return model_class.from_pretrained(
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2262, in from_pretrained
 load_in_8bit = quantization_config.load_in_8bit
AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit'

2023-08-16T11:28:47+0000 [ERROR] [runner:llm-llama-runner:1] Application startup failed. Exiting.
2023-08-16T11:28:57+0000 [ERROR] [runner:llm-llama-runner:1] An exception occurred while instantiating runner 'llm-llama-runner', see details below:
2023-08-16T11:28:57+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
 self._set_handle(LocalRunnerRef)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
 runner_handle = handle_class(self, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
 self._runnable = runner.runnable_class(**runner.runnable_init_params) # type: ignore
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
 if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
 model = self.load_model(*self._model_decls, **self._model_attrs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
 return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
 return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 156, in load_model
 model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
 return model_class.from_pretrained(
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2262, in from_pretrained
 load_in_8bit = quantization_config.load_in_8bit
AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit'

2023-08-16T11:28:57+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
 async with self.lifespan_context(app) as maybe_state:
 File "/opt/conda/envs/inference/lib/python3.10/contextlib.py", line 199, in __aenter__
 return await anext(self.gen)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
 on_startup()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 312, in init_local
 raise e
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
 self._set_handle(LocalRunnerRef)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
 runner_handle = handle_class(self, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
 self._runnable = runner.runnable_class(**runner.runnable_init_params) # type: ignore
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
 if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
 model = self.load_model(*self._model_decls, **self._model_attrs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
 return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
 return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 156, in load_model
 model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
 return model_class.from_pretrained(
 File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2262, in from_pretrained
 load_in_8bit = quantization_config.load_in_8bit
AttributeError: 'BaseQuantizeConfig' object has no attribute 'load_in_8bit'

2023-08-16T11:28:57+0000 [ERROR] [runner:llm-llama-runner:1] Application startup failed. Exiting.
```

### Environment

- `transformers` version: 4.31.0
- Platform: Linux-5.10.0-24-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes, A100 GPU
- Using distributed or parallel set-up in script?: No
openllm==0.2.25
bentoml==1.1.1

### System information (Optional)

a2-highgpu-1g from GCP with 1xA100 40GB

```[tasklist]
### Tasks
```

**Comment by aliozts** [comment]
2023-08-24T09:01:17+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service:svc" can be accessed at http://localhost:3000/metrics.
2023-08-24T09:01:17+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
2023-08-24T09:01:25+0000 [ERROR] [runner:llm-llama-runner:1] An exception occurred while instantiating runner 'llm-llama-runner', see details below:
2023-08-24T09:01:25+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
    self._set_handle(LocalRunnerRef)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
    runner_handle = handle_class(self, *args, **kwargs)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
    self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
    if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
    model = self.load_model(*self._model_decls, **self._model_attrs)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
    return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
    return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 154, in load_model
    model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2358, in from_pretrained
    raise ValueError(
ValueError: Invalid type for `quantization_config`: <class 'auto_gptq.modeling._base.BaseQuantizeConfig'>. Should be a `dict` or a `BitsAndBytesConfig` instance.

2023-08-24T09:01:25+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/conda/envs/inference/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
    on_startup()
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 312, in init_local
    raise e
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 302, in init_local
    self._set_handle(LocalRunnerRef)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 145, in _set_handle
    runner_handle = handle_class(self, *args, **kwargs)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 24, in __init__
    self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 1027, in __init__
    if not self.model: raise RuntimeError("Failed to load the model correctly (See traceback above)")
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 789, in model
    model = self.load_model(*self._model_decls, **self._model_attrs)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/_llm.py", line 314, in wrapper
    return f(self, *(*model_decls, *decls), **{**model_attrs, **attrs})
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 77, in caller
    return getattr(importlib.import_module(f".{llm.runtime}", __name__), fn)(llm, *args, **kwargs)
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 154, in load_model
    model = infer_autoclass_from_llm(llm, config).from_pretrained(llm._bentomodel.path, *decls, config=config, trust_remote_code=llm.__llm_trust_remote_code__, device_map=device_map, **hub_attrs, **attrs).eval()
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/envs/inference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2358, in from_pretrained
    raise ValueError(
ValueError: Invalid type for `quantization_config`: <class 'auto_gptq.modeling._base.BaseQuantizeConfig'>. Should be a `dict` or a `BitsAndBytesConfig` instance.

Error has changed to this with 
```
openllm=0.2.26
auto-gptq==0.4.1+cu118
```

**Comment by aarnphm** [comment]
please try again with latest release. I have migrate gptq support to use official gptq support from optimum
