### ISSUE TITLE
bug: 'IndexError: list index out of range' on a dataset

### ISSUE THREAD

**Issue by thistleknot** [bentoml/OpenLLM#236]
If I set leave condition False, I get an error (i.e. AutoGPTQForCausalLM)

I'm not doing anything else different based on this condition.  Simply loading the model.

I am using my own custom trainer however (MeZO).  I don't know if that would have something to do with it.

```
quantize_config = BaseQuantizeConfig(
    bits=2,  # quantize model to 4-bit
    group_size=128,  # it is recommended to set the value to 128
    desc_act=False,  # set to False can significantly speed up inference but the perplexity may slightly bad
)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=args["load_in_4bit"],
    bnb_4bit_use_double_quant=args["bnb_4bit_use_double_quant"],
    bnb_4bit_quant_type=args["bnb_4bit_quant_type"],
    bnb_4bit_compute_dtype=eval(args["bnb_4bit_compute_dtype"])
)

lora_config = LoraConfig(
    r=args["lora_r"],
    lora_alpha=args["lora_alpha"],
    lora_dropout=args["lora_dropout"],
    bias=args["lora_bias"],
    task_type=args["lora_task_type"]
)

device_map = {"": 0}

if(False):
    model = AutoModelForCausalLM.from_pretrained(MODEL,quantization_config=bnb_config, device_map=device_map)

    model.gradient_checkpointing_enable()
    model = prepare_model_for_kbit_training(model)

    model = get_peft_model(model, lora_config)
    #needed when updating weights (and saving)?
    model.config.use_cache = False

else:
    #results in error 'IndexError: list index out of range' on a dataset
    model = AutoGPTQForCausalLM.from_pretrained(MODEL,quantize_config=quantize_config, device_map = device_map)
    #model = AutoGPTQForCausalLM.from_pretrained(MODEL,quantize_config=quantize_config, device_map = "auto")
```

### Logs

```shell
]/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/formatting/formatting.py:100: RuntimeWarning: divide by zero encountered in remainder
  return table.fast_gather(key % table.num_rows)
Traceback (most recent call last):
  File "/home/user/TrainLLMv2/mezo.py", line 258, in <module>
    trainer.train()
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TrainLLMv2/functions.py", line 441, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/accelerate/data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/arrow_dataset.py", line 2807, in __getitems__
    batch = self.__getitem__(keys)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/arrow_dataset.py", line 2803, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/arrow_dataset.py", line 2787, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/formatting/formatting.py", line 588, in query_table
    pa_subtable = _query_table_with_indices_mapping(table, key, indices=indices)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/formatting/formatting.py", line 75, in _query_table_with_indices_mapping
    return _query_table(table, [indices.fast_slice(i, 1).column(0)[0].as_py() for i in key])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/formatting/formatting.py", line 100, in _query_table
    return table.fast_gather(key % table.num_rows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/table.py", line 134, in fast_gather
    [
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/datasets/table.py", line 135, in <listcomp>
    self._batches[batch_idx].slice(i - self._offsets[batch_idx], 1)
    ~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/user/TrainLLMv2/wandb/offline-run-20230819_075217-8t57ll2y
wandb: Find logs at: ./wandb/offline-run-20230819_075217-8t57ll2y/logs
```
```


### Environment

python 3.11

(env-MeZo) [root@pve-m7330 TrainLLMv2]# pip list installed
Package            Version
------------------ ------------
accelerate         0.21.0
aiohttp            3.8.5
aiosignal          1.3.1
appdirs            1.4.4
async-timeout      4.0.3
attrs              23.1.0
auto-gptq          0.3.1
autopep8           2.0.2
bitsandbytes       0.41.1
black              23.7.0
certifi            2023.7.22
charset-normalizer 3.2.0
click              8.1.7
cmake              3.25.0
coloredlogs        15.0.1
dataclasses        0.6
datasets           2.14.4
dill               0.3.7
docker-pycreds     0.4.0
filelock           3.12.2
frozenlist         1.4.0
fsspec             2023.6.0
gitdb              4.0.10
GitPython          3.1.32
huggingface-hub    0.16.4
humanfriendly      10.0
idna               3.4
Jinja2             3.1.2
joblib             1.3.2
lit                15.0.7
MarkupSafe         2.1.2
mpmath             1.2.1
multidict          6.0.4
multiprocess       0.70.15
mypy-extensions    1.0.0
networkx           3.0
numpy              1.25.2
optimum            1.11.3.dev0
packaging          23.1
pandas             2.0.3
pathspec           0.11.2
pathtools          0.1.2
peft               0.4.0
Pillow             9.3.0
pip                22.3.1
platformdirs       3.10.0
protobuf           4.24.0
psutil             5.9.5
pyarrow            12.0.1
pycodestyle        2.11.0
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0.1
regex              2023.8.8
requests           2.31.0
rouge              1.0.1
safetensors        0.3.2
scikit-learn       1.3.0
scipy              1.11.1
sentencepiece      0.1.99
sentry-sdk         1.29.2
setproctitle       1.3.2
setuptools         65.5.1
six                1.16.0
sklearn            0.0.post7
smmap              5.0.0
sympy              1.11.1
threadpoolctl      3.2.0
tokenizers         0.13.3
torch              2.0.1+cu118
torchaudio         2.0.2+cu118
torchvision        0.15.2+cu118
tqdm               4.66.1
transformers       4.31.0
triton             2.0.0
typing_extensions  4.7.1
tzdata             2023.3
urllib3            2.0.4
wandb              0.15.8
xxhash             3.3.0
yarl               1.9.2



### System information (Optional)

rocky linux 9
quadro 5200

**Comment by thistleknot** [comment]
wrong repo

**Comment by goga334** [comment]
> wrong repo

Hi)
I'm facing the same issue. Could you please tell me whether the problem was solved and where to look for solution?

**Comment by rui-ye** [comment]
same issue (not running this repo). anyone knows how to fix it?
