### ISSUE TITLE
bug: 'Text' is not designed to take any args or kwargs during initialization.

### ISSUE THREAD

**Issue by gbmarc1** [bentoml/OpenLLM#248]
### Describe the bug

On the main branch, unexpected error occurs for llama by doing 

- `openllm build llama`
 -> `    raise BentoMLException(
bentoml.exceptions.BentoMLException: 'Text' is not designed to take any args or kwargs during initialization.`
or
- `openllm start NousResearch/Llama-2-7b-hf`
-> `Error: [bentoml-cli] `serve` failed: 'Text' is not designed to take any args or kwargs during initialization.`

### To reproduce

1. git clone https://github.com/bentoml/OpenLLM.git
2. git checkout 9e371d2eade0365faca02f3359125df3cea1b736
3. pip install "OpenLLM/openllm-python[llama]" protobuf==3.20.2 bitsandbytes==0.41.0
4. openllm build llama

### Logs

```shell
Downloading (…)lve/main/config.json: 100%|██████████| 583/583 [00:00<00:00, 2.94MB/s]
Downloading (…)okenizer_config.json: 100%|██████████| 746/746 [00:00<00:00, 2.94MB/s]
Downloading tokenizer.model: 100%|██████████| 500k/500k [00:00<00:00, 30.4MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 1.84M/1.84M [00:00<00:00, 7.52MB/s]
Downloading (…)in/added_tokens.json: 100%|██████████| 21.0/21.0 [00:00<00:00, 93.8kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 435/435 [00:00<00:00, 2.14MB/s]
Downloading (…)neration_config.json: 100%|██████████| 179/179 [00:00<00:00, 988kB/s]
Downloading (…)fetensors.index.json: 100%|██████████| 26.8k/26.8k [00:00<00:00, 79.7MB/s]
Downloading (…)model.bin.index.json: 100%|██████████| 26.8k/26.8k [00:00<00:00, 36.1MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████| 3.50G/3.50G [00:18<00:00, 187MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████| 9.98G/9.98G [00:44<00:00, 224MB/s]
Fetching 11 files: 100%|██████████| 11/11 [00:45<00:00,  4.16s/it][00:18<00:52, 123MB/s]
Building Bento for 'llama'fetensors: 100%|█████████▉| 9.95G/9.98G [00:44<00:00, 266MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/openllm", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openllm/cli/entrypoint.py", line 178, in wrapper
    try: return func(*args, **attrs)
  File "/usr/local/lib/python3.10/dist-packages/openllm/cli/entrypoint.py", line 159, in wrapper
    return_value = func(*args, **attrs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openllm/cli/entrypoint.py", line 143, in wrapper
    return f(*args, **attrs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openllm/cli/entrypoint.py", line 498, in build_command
    except Exception as err: raise err from None
  File "/usr/local/lib/python3.10/dist-packages/openllm/cli/entrypoint.py", line 493, in build_command
    bento = bundle.create_bento(
  File "/usr/local/lib/python3.10/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.10/dist-packages/openllm/bundle/_package.py", line 126, in create_bento
    bento = bentoml.Bento.create(build_config=build_config, version=bento_tag.version, build_ctx=llm_fs.getsyspath("/"))
  File "/usr/local/lib/python3.10/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/bento/bento.py", line 186, in create
    svc = import_service(
  File "/usr/local/lib/python3.10/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/service/loader.py", line 137, in import_service
    module = importlib.import_module(module_name, package=working_dir)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/tmpjr0kawdnllm_llama/generated_llama_service.py", line 33, in <module>
  File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/io_descriptors/text.py", line 95, in __init__
    raise BentoMLException(
bentoml.exceptions.BentoMLException: 'Text' is not designed to take any args or kwargs during initialization.
```
```


### Environment

openllm[llama]@9e371d2eade0365faca02f3359125df3cea1b736
protobuf==3.20.2
bitsandbytes==0.41.0

### System information (Optional)

Linux SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
GPU: NVIDIA L4

**Comment by gbmarc1** [comment]
Problem solved with 0.2.27
