### ISSUE TITLE
bug: "RuntimeError: No CUDA GPUs are available"

### ISSUE THREAD

**Issue by vvvlll93** [bentoml/OpenLLM#307]
### Describe the bug

Hi,

I'm trying to run inference against llama2, more precisely "meta-llama/Llama-2-7b-chat-hf".

I installed torch 2.0.1+cu118 and cuda 11.8.

I followed instruction in the repo for meta model and executed the following command : 
`pip install "openllm[llama]"`

`openllm start llama --model-id meta-llama/Llama-2-7b-chat-hf`
`export OPENLLM_ENDPOINT=http://localhost:3000`
`openllm query 'What are large language models?'`
 
But in response i get this error `RuntimeError: No CUDA GPUs are available`

I tried to run the following code to check if cuda is available (which was previously not) 
`import torch`
`print("Torch version:",torch.__version__)`
`print("Is CUDA enabled?",torch.cuda.is_available())`

Which respond `True`. 
I checked the compatibility for my GPU on the NVIDIA website and everything seems to be ok. I installed CUDA toolkit v11.8 without problem, here is the result of the `nvcc --version`:
```nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

I don't really understand. I believe it might be due to the way torch works by coming with its own CUDA distribution, but i don't really know if 1) that's the case and 2) how to solve this issue.

If you have any clue for what i can try next, it would be really nice. Thanks !

### To reproduce

Following the step for running the llama category example in the documentation.

### Logs

```shell
2023-09-08T16:09:37+0200 [INFO] [runner:llm-llama-runner:1] 127.0.0.1:62208 (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 0.839ms (trace=7802372af709591d5666c1d070221208,span=2ea0af78c63f2277,sampled=1,service.name=llm-llama-runner)
2023-09-08T16:09:37+0200 [INFO] [api_server:llm-llama-service:3] 127.0.0.1:62207 (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 148.504ms (trace=7802372af709591d5666c1d070221208,span=9bb910ee4b02f8b2,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:39+0200 [INFO] [runner:llm-llama-runner:1] 127.0.0.1:62211 (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 0.244ms (trace=1079fc164ea2a5abfa2a2254eb9d65f2,span=5c3f5c2fa624ce21,sampled=1,service.name=llm-llama-runner)
2023-09-08T16:09:39+0200 [INFO] [api_server:llm-llama-service:6] 127.0.0.1:62210 (scheme=http,method=GET,path=/readyz,type=,length=) (status=200,type=text/plain; charset=utf-8,length=1) 83.950ms (trace=1079fc164ea2a5abfa2a2254eb9d65f2,span=d9c56eb598a9aa13,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:41+0200 [INFO] [api_server:llm-llama-service:20] 127.0.0.1:62214 (scheme=http,method=GET,path=/docs.json,type=,length=) (status=200,type=application/json,length=11043) 19.957ms (trace=38536d251419840dd90ff9bc50a5dce1,span=eb0b0fb916a69395,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:43+0200 [INFO] [api_server:llm-llama-service:5] 127.0.0.1:62218 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=916) 20.580ms (trace=c42ecea9390d41678db2d756189d5a18,span=c07815cd8dceb9a5,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:43+0200 [INFO] [api_server:llm-llama-service:5] 127.0.0.1:62218 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=916) 1.022ms (trace=911f85c93567c02020288ddbeea72bc7,span=4f054e00a02b5032,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:43+0200 [INFO] [api_server:llm-llama-service:5] 127.0.0.1:62218 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=916) 0.686ms (trace=4f90d7200223a2031fb765832beb629b,span=e79e67ff99b4d8ff,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:43+0200 [INFO] [api_server:llm-llama-service:5] 127.0.0.1:62218 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=916) 0.772ms (trace=c16d006c6a34141f84e8cadbb6308518,span=aa1c1a69ed44cfbf,sampled=1,service.name=llm-llama-service)
2023-09-08T16:09:43+0200 [INFO] [api_server:llm-llama-service:5] 127.0.0.1:62218 (scheme=http,method=POST,path=/v1/metadata,type=text/plain; charset=utf-8,length=0) (status=200,type=application/json,length=916) 0.657ms (trace=204b20566e282d065718d343c2f16c4e,span=a42b26f60b9d99d4,sampled=1,service.name=llm-llama-service)
Traceback (most recent call last):
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\runner_app.py", line 281, in infer_single
    ret = await runner_method.async_run(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner_handle\local.py", line 62, in async_run_method
    return await anyio.to_thread.run_sync(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runnable.py", line 143, in method
    return self.func(obj, *args, **kwargs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 1188, in generate
    return self.generate(prompt, **attrs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 946, in generate
    for it in self.generate_iterator(prompt, **attrs):
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 982, in generate_iterator
    torch.cuda.synchronize()
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\torch\cuda\__init__.py", line 686, in synchronize
    _lazy_init()
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2023-09-08T16:09:44+0200 [ERROR] [api_server:llm-llama-service:5] Exception on /v1/generate [POST] (trace=bfa0fce87ad6a59e62132b1f4322840c,span=03ee30b82a9232df,sampled=1,service.name=llm-llama-service)
Traceback (most recent call last):
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http_app.py", line 341, in api_func
    output = await api.func(*args)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\Lib\site-packages\openllm\_service.py", line 50, in generate_v1
    responses = await runner.generate.async_run(qa_inputs.prompt, **{'adapter_name': qa_inputs.adapter_name, **config})
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner_handle\remote.py", line 242, in async_run_method
    raise RemoteException(
bentoml.exceptions.RemoteException: An unexpected exception occurred in remote runner llm-llama-runner: [500] Internal Server Error
2023-09-08T16:09:44+0200 [ERROR] [runner:llm-llama-runner:1] Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\traffic.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\opentelemetry\instrumentation\asgi\__init__.py", line 580, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\instruments.py", line 252, in __call__
    await self.app(scope, receive, wrapped_send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\access.py", line 126, in __call__
    await self.app(scope, receive, wrapped_send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 70, in app
    response = await func(request)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\runner_app.py", line 306, in _request_handler
    payload = await infer(params)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\marshal\dispatcher.py", line 182, in _func
    raise r
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\marshal\dispatcher.py", line 377, in outbound_call
    outputs = await self.callback(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\runner_app.py", line 281, in infer_single
    ret = await runner_method.async_run(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner_handle\local.py", line 62, in async_run_method
    return await anyio.to_thread.run_sync(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runnable.py", line 143, in method
    return self.func(obj, *args, **kwargs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 1188, in generate
    return self.generate(prompt, **attrs)
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 946, in generate
    for it in self.generate_iterator(prompt, **attrs):
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 982, in generate_iterator
    torch.cuda.synchronize()
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\torch\cuda\__init__.py", line 686, in synchronize
    _lazy_init()
  File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\applications.py", line 116, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\traffic.py", line 32, in __call__
  |     await resp(scope, receive, send)
  |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\traffic.py", line 26, in __call__
    |     await self.app(scope, receive, send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\opentelemetry\instrumentation\asgi\__init__.py", line 580, in __call__
    |     await self.app(scope, otel_receive, otel_send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\instruments.py", line 252, in __call__
    |     await self.app(scope, receive, wrapped_send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\http\access.py", line 126, in __call__
    |     await self.app(scope, receive, wrapped_send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    |     raise exc
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 746, in __call__
    |     await route.handle(scope, receive, send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 75, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    |     raise exc
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\starlette\routing.py", line 70, in app
    |     response = await func(request)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\runner_app.py", line 306, in _request_handler
    |     payload = await infer(params)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\marshal\dispatcher.py", line 182, in _func
    |     raise r
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\marshal\dispatcher.py", line 377, in outbound_call
    |     outputs = await self.callback(
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\server\runner_app.py", line 281, in infer_single
    |     ret = await runner_method.async_run(
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner.py", line 55, in async_run
    |     return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runner_handle\local.py", line 62, in async_run_method
    |     return await anyio.to_thread.run_sync(
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    |     return await future
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    |     result = context.run(func, *args)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\bentoml\_internal\runner\runnable.py", line 143, in method
    |     return self.func(obj, *args, **kwargs)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 1188, in generate
    |     return self.generate(prompt, **attrs)
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 946, in generate
    |     for it in self.generate_iterator(prompt, **attrs):
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\openllm\_llm.py", line 982, in generate_iterator
    |     torch.cuda.synchronize()
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\torch\cuda\__init__.py", line 686, in synchronize
    |     _lazy_init()
    |   File "C:\Users\21202441t\PycharmProjects\EvaluationEEL\venv\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    |     torch._C._cuda_init()
    | RuntimeError: No CUDA GPUs are available
```

### Environment

accelerate                                   0.22.0
aiohttp                                      3.8.5
aiosignal                                    1.3.1
anyio                                        4.0.0
appdirs                                      1.4.4
asgiref                                      3.7.2
async-timeout                                4.0.3
attrs                                        23.1.0
beautifulsoup4                               4.12.2
bentoml                                      1.1.6
bitsandbytes                                 0.41.1
boto3                                        1.28.43
botocore                                     1.31.43
bpemb                                        0.3.4
build                                        1.0.3
cattrs                                       23.1.2
certifi                                      2023.7.22
charset-normalizer                           3.2.0
circus                                       0.18.0
click                                        8.1.7
click-option-group                           0.5.6
cloudpickle                                  2.2.1
colorama                                     0.4.6
coloredlogs                                  15.0.1
conllu                                       4.5.3
contextlib2                                  21.6.0
contourpy                                    1.1.0
cuda-python                                  12.2.0
cycler                                       0.11.0
Cython                                       3.0.2
datasets                                     2.14.5
deepmerge                                    1.1.0
Deprecated                                   1.2.14
dill                                         0.3.7
diskcache                                    5.6.3
emoji                                        2.8.0
exceptiongroup                               1.1.3
fairscale                                    0.4.13
fastcore                                     1.5.29
filelock                                     3.12.3
filetype                                     1.2.0
flair                                        0.12.2
fonttools                                    4.42.1
frozenlist                                   1.4.0
fs                                           2.4.16
fsspec                                       2023.6.0
ftfy                                         6.1.1
future                                       0.18.3
gdown                                        4.4.0
gensim                                       4.3.2
ghapi                                        1.0.4
h11                                          0.14.0
httpcore                                     0.17.3
httpx                                        0.24.1
huggingface-hub                              0.16.4
humanfriendly                                10.0
hyperopt                                     0.2.7
idna                                         3.4
importlib-metadata                           6.0.1
importlib-resources                          6.0.1
inflection                                   0.5.1
Janome                                       0.5.0
Jinja2                                       3.1.2
jmespath                                     1.0.1
joblib                                       1.3.2
kiwisolver                                   1.4.5
langdetect                                   1.0.9
llama-cpp-python                             0.1.83
lxml                                         4.9.3
markdown-it-py                               3.0.0
MarkupSafe                                   2.1.3
matplotlib                                   3.7.2
mdurl                                        0.1.2
more-itertools                               10.1.0
mpld3                                        0.3
mpmath                                       1.3.0
multidict                                    6.0.4
multiprocess                                 0.70.15
mypy-extensions                              1.0.0
nereval                                      0.2.5
nervaluate                                   0.1.8
networkx                                     3.1
numpy                                        1.24.4
openllm                                      0.3.3
openllm-client                               0.3.3
openllm-core                                 0.3.3
opentelemetry-api                            1.18.0
opentelemetry-instrumentation                0.39b0
opentelemetry-instrumentation-aiohttp-client 0.39b0
opentelemetry-instrumentation-asgi           0.39b0
opentelemetry-sdk                            1.18.0
opentelemetry-semantic-conventions           0.39b0
opentelemetry-util-http                      0.39b0
optimum                                      1.13.0
orjson                                       3.9.6
packaging                                    23.1
pandas                                       2.0.3
pathspec                                     0.11.2
Pillow                                       10.0.0
pip                                          22.3.1
pip-requirements-parser                      32.0.1
pip-tools                                    7.3.0
pptree                                       3.1
prometheus-client                            0.17.1
protobuf                                     4.24.2
psutil                                       5.9.5
py4j                                         0.10.9.7
pyarrow                                      13.0.0
pydantic                                     1.10.12
Pygments                                     2.16.1
pynvml                                       11.5.0
pyparsing                                    3.0.9
pyproject_hooks                              1.0.0
pyreadline3                                  3.4.1
PySocks                                      1.7.1
python-dateutil                              2.8.2
python-json-logger                           2.0.7
python-multipart                             0.0.6
pytorch_revgrad                              0.2.0
pytz                                         2023.3.post1
PyYAML                                       6.0.1
pyzmq                                        25.1.1
regex                                        2023.8.8
requests                                     2.31.0
rich                                         13.5.2
s3transfer                                   0.6.2
safetensors                                  0.3.3
schema                                       0.7.5
scikit-learn                                 1.3.0
scipy                                        1.10.1
segtok                                       1.5.11
sentencepiece                                0.1.99
setuptools                                   65.5.1
simphile                                     1.0.2
simple-di                                    0.1.5
six                                          1.16.0
smart-open                                   6.4.0
sniffio                                      1.3.0
soupsieve                                    2.5
sqlitedict                                   2.1.0
starlette                                    0.31.1
sympy                                        1.12
tabulate                                     0.9.0
threadpoolctl                                3.2.0
tokenizers                                   0.13.3
tomli                                        2.0.1
torch                                        2.0.1
Unidecode                                    1.3.6
urllib3                                      1.26.16
uvicorn                                      0.23.2
watchfiles                                   0.20.0
wcwidth                                      0.2.6
wheel                                        0.38.4
Wikipedia-API                                0.6.0
wrapt                                        1.15.0
xxhash                                       3.3.0
yarl                                         1.9.2
zipp                                         3.16.2

**Comment by aarnphm** [comment]
We have been seeing this issue persistent among Windows machine. Can you try running this in WSL for now?

**Comment by vvvlll93** [comment]
Thanks for the answer. I _resetup_ OpenLLM using WSL and I no longer have the same error, now it's `httpx.ReadTimeout: timed out`. I'll dig into it.

**Comment by bojiang** [comment]
Feel free to reopen it
