### ISSUE TITLE
bug: Built runner has no default mapping

### ISSUE THREAD

**Issue by QLutz** [bentoml/OpenLLM#348]
### Describe the bug

Thanks for the last release ! It really delivers a lot of amazing features !

The problem I have occurs when building a runner using the (experimental) fine-tuning support with a LLaMa2 13B model.

I use three locally stored adapters and running the API using the `openllm start llama ...` command works fine.

Changing to the `openllm built llama ...` command does not yield any errors either. Dockerizing the resulting Bento also works fine.

However, when trying to run the resulting image, I get an error on startup

### To reproduce

```shell
openllm build llama --adapter-id ./ad1_default --adapter-id ./ad2_task1:task1 --adapter-id ./ad3_task2:task2 --build_ctx .
bentoml containerize my-service:some_long_and_complicated_id --opt progress=plain
docker run --rm -v /some/path/bentoml_configuration.yaml:/home/bentoml/configuration.yml -e BENTOML_CONFIG=/home/bentoml/configuration.yml -p 3000:3000 my-service:some_long_and_complicated_id
```

### Logs

```shell
2023-09-13T14:27:25+0000 [DEBUG] [runner:llm-llama-runner:1] Creating converter from 7 to 5
2023-09-13T14:27:25+0000 [DEBUG] [runner:llm-llama-runner:1] Creating converter from 5 to 7
2023-09-13T14:27:25+0000 [DEBUG] [runner:llm-llama-runner:1] Creating converter from 7 to 5
2023-09-13T14:27:25+0000 [DEBUG] [runner:llm-llama-runner:1] Creating converter from 5 to 7
Loading checkpoint shards: 100%|██████████| 11/11 [00:02<00:00,  5.27it/s]
2023-09-13T14:27:38+0000 [INFO] [runner:llm-llama-runner:1] Applying LoRA to llm-llama-runner...
/opt/conda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
2023-09-13T14:27:39+0000 [ERROR] [runner:llm-llama-runner:1] An exception occurred while instantiating runner 'llm-llama-runner', see details below:
2023-09-13T14:27:39+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
    self._set_handle(LocalRunnerRef)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
    runner_handle = handle_class(self, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
    self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 1165, in __init__
    self.apply_adapter(inference_mode=True, load_adapters='all')
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 820, in apply_adapter
    self.__llm_model__ = self._wrap_default_peft_model(adapter_mapping, inference_mode=inference_mode)
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 843, in _wrap_default_peft_model
    raise ValueError("There is no 'default' mapping. Please check the adapter mapping and report this bug to the OpenLLM team.")
ValueError: There is no 'default' mapping. Please check the adapter mapping and report this bug to the OpenLLM team.

2023-09-13T14:27:39+0000 [ERROR] [runner:llm-llama-runner:1] Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/conda/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
    on_startup()
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 317, in init_local
    raise e
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
    self._set_handle(LocalRunnerRef)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
    runner_handle = handle_class(self, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
    self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 1165, in __init__
    self.apply_adapter(inference_mode=True, load_adapters='all')
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 820, in apply_adapter
    self.__llm_model__ = self._wrap_default_peft_model(adapter_mapping, inference_mode=inference_mode)
  File "/opt/conda/lib/python3.9/site-packages/openllm/_llm.py", line 843, in _wrap_default_peft_model
    raise ValueError("There is no 'default' mapping. Please check the adapter mapping and report this bug to the OpenLLM team.")
ValueError: There is no 'default' mapping. Please check the adapter mapping and report this bug to the OpenLLM team.

2023-09-13T14:27:39+0000 [ERROR] [runner:llm-llama-runner:1] Application startup failed. Exiting.
```

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.6
`python`: 3.8.10
`platform`: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
`uid_gid`: 1000:1000
<details><summary><code>pip_packages</code></summary>

<br>

```
absl-py==0.15.0
accelerate==0.22.0
aiohttp==3.8.5
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asgiref==3.7.2
astunparse==1.6.2
async-timeout==4.0.3
atomicwrites==1.1.5
attrs==23.1.0
Automat==0.8.0
Babel==2.10.3
backcall==0.1.0
beautifulsoup4==4.8.2
bentoml==1.1.6
bitsandbytes==0.41.1
bleach==3.1.1
blinker==1.4
blosc==1.7.0
bottle==0.12.15
build==1.0.3
cachetools==4.0.0
caffe==1.0.0
cattrs==23.1.2
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
charset-normalizer==2.1.1
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloud-init==22.3.4
cloudpickle==2.2.1
cmake==3.27.4.1
colorama==0.4.3
coloredlogs==15.0.1
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contextlib2==21.6.0
cryptography==2.8
ctop==1.0.0
cuda-python==12.2.0
cycler==0.10.0
Cython==0.29.14
dask==2.8.1+dfsg
datasets==2.14.5
dbus-python==1.2.16
decorator==4.4.2
deepmerge==1.1.0
defusedxml==0.6.0
Deprecated==1.2.14
dill==0.3.7
distlib==0.3.0
distro==1.4.0
distro-info===0.23ubuntu1
docker==4.1.0
entrypoints==0.3
et-xmlfile==1.0.1
exceptiongroup==1.1.3
fairscale==0.4.13
fastapi==0.103.1
fastcore==1.5.29
fastjsonschema==2.16.2
filelock==3.0.12
filetype==1.2.0
flake8==3.7.9
flatbuffers==1.12
fonttools==4.38.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.6.0
future==0.18.2
gast==0.4.0
ghapi==1.0.4
Glances==3.1.3
google-auth==1.5.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.58.0
h11==0.14.0
h5py==2.10.0
html5lib==1.0.1
htmlmin==0.1.12
httpcore==0.18.0
httplib2==0.14.0
httpx==0.25.0
huggingface-hub==0.17.1
humanfriendly==10.0
hyperlink==19.0.0
icdiff==1.9.5
idna==2.8
ImageHash==4.3.1
imageio==2.4.1
importlib-metadata==6.0.1
incremental==16.10.1
inflection==0.5.1
influxdb==5.2.0
iotop==0.6
ipykernel==5.2.0
ipython==7.13.0
ipython_genutils==0.2.0
ipywidgets==8.0.2
jdcal==1.0
jedi==0.15.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.10
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
jupyter-console==6.0.0
jupyter-server==1.21.0
jupyter_client==7.4.4
jupyter_core==4.11.2
jupyterlab==3.5.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
jupyterlab_server==2.16.1
kaptan==0.5.10
keras==2.9.0
Keras-Preprocessing==1.1.2
keyring==18.0.1
kiwisolver==1.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
libtmux==0.8.2
lit==16.0.6
locket==0.2.0
lxml==4.5.0
Mako==1.1.0
Markdown==3.1.1
markdown-it-py==3.0.0
MarkupSafe==2.1.1
matplotlib==3.5.3
mccabe==0.6.1
mdurl==0.1.2
missingno==0.5.1
mistune==2.0.4
more-itertools==4.2.0
mpi4py==3.0.3
mpmath==1.3.0
msgpack==1.0.5
multidict==6.0.4
multimethod==1.9
multiprocess==0.70.15
mypy-extensions==1.0.0
nbclassic==0.4.7
nbclient==0.7.0
nbconvert==7.2.2
nbformat==5.7.0
nest-asyncio==1.5.6
netifaces==0.10.4
networkx==2.4
ninja==1.11.1
nose==1.3.7
notebook==6.0.3
notebook_shim==0.2.0
numexpr==2.7.1
numpy==1.23.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-ml-py==7.352.0
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.1.0
olefile==0.46
openllm==0.3.3
openllm-client==0.3.3
openllm-core==0.3.3
openpyxl==3.0.3
opentelemetry-api==1.18.0
opentelemetry-instrumentation==0.39b0
opentelemetry-instrumentation-aiohttp-client==0.39b0
opentelemetry-instrumentation-asgi==0.39b0
opentelemetry-sdk==1.18.0
opentelemetry-semantic-conventions==0.39b0
opentelemetry-util-http==0.39b0
opt-einsum==3.3.0
optimum==1.13.1
orjson==3.9.7
packaging==23.1
pandas==1.5.1
pandas-profiling==3.4.0
pandocfilters==1.4.2
parameterized==0.7.0
parso==0.5.2
partd==1.0.0
pathspec==0.11.2
patsy==0.5.3
peft==0.5.0
pexpect==4.6.0
phik==0.12.2
pickleshare==0.7.5
Pillow==7.0.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
pluggy==0.13.0
ply==3.11
prometheus-client==0.17.1
prompt-toolkit==2.0.10
protobuf==3.20.3
psutil==5.5.1
ptyprocess==0.7.0
py==1.8.1
pyarrow==13.0.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycodestyle==2.5.0
pycparser==2.19
pycryptodomex==3.6.1
pycuda==2019.1.2
pydantic==1.10.2
pydot==1.4.1
pyflakes==2.1.1
Pygments==2.13.0
PyGObject==3.36.0
pygpu==0.7.6
PyHamcrest==1.9.0
pyinotify==0.9.6
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pynvml==11.5.0
pyOpenSSL==19.0.0
pyparsing==2.4.6
pyproject_hooks==1.0.0
pyrsistent==0.15.5
pyserial==3.4
pysmi==0.3.2
pysnmp==4.4.6
pystache==0.5.4
pytest==4.6.9
python-apt==2.0.0+ubuntu0.20.4.8
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
python-json-logger==2.0.7
python-multipart==0.0.6
pytools==2019.1.1
pytz==2022.5
PyWavelets==0.5.1
PyYAML==5.3.1
pyzmq==24.0.1
ray==2.6.3
regex==2023.8.8
requests==2.28.1
requests-oauthlib==1.0.0
requests-unixsocket==0.2.0
rich==13.5.2
rsa==4.0
safetensors==0.3.3
schema==0.7.5
scikit-cuda==0.5.3
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.9.3
seaborn==0.12.1
SecretStorage==2.3.1
Send2Trash==1.8.0
sentencepiece==0.1.99
service-identity==18.1.0
simple-di==0.1.5
simplejson==3.16.0
six==1.14.0
sniffio==1.3.0
sos==4.4
soupsieve==1.9.5
ssh-import-id==5.10
starlette==0.27.0
statsmodels==0.13.2
sympy==1.12
systemd-python==234
tables==3.6.1
tabulate==0.9.0
tangled-up-in-unicode==0.2.0
tensorboard==2.9.1
tensorflow-estimator==2.9.0
tensorflow-gpu==2.9.1
termcolor==1.1.0
terminado==0.17.0
testpath==0.4.4
Theano==1.0.4
tinycss2==1.2.1
tmuxp==1.5.4
tokenizers==0.13.3
tomli==2.0.1
toolz==0.9.0
torch==2.0.1
torchvision==0.13.1
tornado==6.2
tqdm==4.64.1
traitlets==5.5.0
transformers==4.33.1
triton==2.0.0
trl==0.7.1
Twisted==18.9.0
typing_extensions==4.7.1
ubuntu-advantage-tools==27.11.2
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
uvicorn==0.23.2
virtualenv==20.0.17
visions==0.7.5
vllm==0.1.7
wadllib==1.3.3
watchfiles==0.20.0
wcwidth==0.1.8
webencodings==0.5.1
websocket-client==0.53.0
Werkzeug==0.16.1
widgetsnbextension==4.0.3
wrapt==1.11.2
xformers==0.0.21
xlrd==1.1.0
xlwt==1.3.0
xxhash==3.3.0
yarl==1.9.2
zipp==1.0.0
zope.interface==4.7.1
```

</details>

- `transformers` version: 4.33.1
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.17.1
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): 2.9.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### System information (Optional)

4xA6000 instance from LambdaLabs

**Comment by aarnphm** [comment]
Got it. Thanks for reporting back. I believe the default adapters is not correctly set in this case. I will create a fix for this.
