### ISSUE TITLE
How to load a model locally?

### ISSUE THREAD

**Issue by mxdlzg** [bentoml/OpenLLM#418]
My server have no net connection. 

How can I manually download a model from Hugging Face into OpenLLM?

**Comment by aarnphm** [comment]
`--model-id` accepts local path

**Comment by mxdlzg** [comment]
> `--model-id` accepts local path
> 
> For example:
> 
> ```shell
> openllm start llama --model-id /path/to/model_dir
> ```

Not working.
Download from :  https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ/tree/gptq-4bit-32g-actorder_True
```
drwxrwxr-x 2 stu1 stu1        4096 Sep   28 18:57 ./
drwxrwxr-x 3 stu1 stu1          43 Sep    28 18:59 ../
-rwxr--r-- 1 stu1 stu1         840 Sep    28 17:36 config.json*
-rwxr--r-- 1 stu1 stu1         137 Sep    28 17:36 generation_config.json*
-rwxr--r-- 1 stu1 stu1        1519 Sep    28 17:36 gitattributes.txt*
-rwxr--r-- 1 stu1 stu1        7020 Sep    28 17:36 LICENSE.txt*
-rwxr--r-- 1 stu1 stu1 40663178600 Sep    28 18:57 model.safetensors*
-rwxr--r-- 1 stu1 stu1         112 Sep    28 17:36 Notice.txt*
-rwxr--r-- 1 stu1 stu1         186 Sep    28 17:36 quantize_config.json*
-rwxr--r-- 1 stu1 stu1       25903 Sep    28 17:36 README.md*
-rwxr--r-- 1 stu1 stu1         411 Sep    28 17:36 special_tokens_map.json*
-rwxr--r-- 1 stu1 stu1         745 Sep    28 17:36 tokenizer_config.json*
-rwxr--r-- 1 stu1 stu1     1842767 Sep    28 17:36 tokenizer.json*
-rwxr--r-- 1 stu1 stu1      499723 Sep    28 17:36 tokenizer.model*
-rwxr--r-- 1 stu1 stu1        4766 Sep    28 17:36 USE_POLICY.md*
```

**Run command:**
`openllm start falcon --model-id /public1/home/stu1/bentoml/models/thebloke/llama-2-70b-chat-gptq --quantize gptq --device 0`

**ERROR**
```
Make sure to have the following dependencies available: ['einops']
Using pad_token, but it is not set yet.
/public1/home/stu1/miniconda3/envs/depllm/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Traceback (most recent call last):
  File "/public1/home/stu1/miniconda3/envs/depllm/lib/python3.11/site-packages/openllm/serialisation/transformers/__init__.py", line 147, in get
    model = bentoml.models.get(llm.tag)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public1/home/stu1/miniconda3/envs/depllm/lib/python3.11/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public1/home/stu1/miniconda3/envs/depllm/lib/python3.11/site-packages/bentoml/models.py", line 45, in get
    return _model_store.get(tag)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/public1/home/stu1/miniconda3/envs/depllm/lib/python3.11/site-packages/bentoml/_internal/store.py", line 146, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'pt-llama-2-70b-chat-gptq:6d2ea9564d97d01ee4c1ce006f3dfe28f38abf5a' is not found in BentoML store <osfs '/public1/home/stu1/bentoml/models'>, you may need to run `bentoml models pull` first
```

**Comment by aarnphm** [comment]
I notice that the models is already in the bentoml home folder. If that is the case you don't need to specify the path, tag `TheBloke/Llama-2-70b-chat-GPTQ` should work.

But it seems like this is a bug from loading local model. I will open a new issue tracking this problem.
