### ISSUE TITLE
Cannot run any models 

### ISSUE THREAD

**Issue by latishab** [bentoml/OpenLLM#520]
(ol) C:\Users\SNS>openllm start falcon --model-id tiiuae/falcon-7b
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████| 1.05k/1.05k [00:00<?, ?B/s]
C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\SNS\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Downloading (…)figuration_falcon.py: 100%|████████████████████████████████████████| 7.16k/7.16k [00:00<00:00, 6.88MB/s]

WARNING: You are currently loading Falcon using legacy code contained in the model repository. Falcon has now been fully ported into the Hugging Face transformers library. For the most up-to-date and high-performance version of the Falcon model code, please update to the latest version of transformers and then load the model without the trust_remote_code=True argument.

Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████| 287/287 [00:00<?, ?B/s]
Downloading (…)/main/tokenizer.json: 100%|████████████████████████████████████████| 2.73M/2.73M [00:01<00:00, 1.80MB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████| 281/281 [00:00<?, ?B/s]
Downloading (…)6/modeling_falcon.py: 100%|████████████████████████████████████████| 56.9k/56.9k [00:00<00:00, 2.25MB/s]
Downloading (…)neration_config.json: 100%|████████████████████████████████████████████| 117/117 [00:00<00:00, 34.7kB/s]
Downloading (…)model.bin.index.json: 100%|████████████████████████████████████████| 16.9k/16.9k [00:00<00:00, 8.46MB/s]
Fetching 10 files:  40%|█████████████████████████▏                                     | 4/10 [17:43<26:35, 265.84s/it]
Downloading (…)l-00002-of-00002.bin: 100%|████████████████████████████████████████| 4.48G/4.48G [50:47<00:00, 1.47MB/s]
Traceback (most recent call last):n: 100%|████████████████████████████████████████| 4.48G/4.48G [50:47<00:00, 1.79MB/s]
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\transformers\__init__.py", line 147, in get
    model = bentoml.models.get(llm.tag)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\simple_di\__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\bentoml\models.py", line 45, in get
    return _model_store.get(tag)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\bentoml\_internal\store.py", line 158, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'pt-tiiuae--falcon-7b:898df1396f35e447d5fe44e0a3ccaaaa69f30d36' is not found in BentoML store <osfs 'C:\Users\SNS\bentoml\models'>, you may need to run `bentoml models pull` first

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\entrypoint.py", line 416, in import_command
    _ref = openllm.serialisation.get(llm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\__init__.py", line 75, in caller
    return getattr(importlib.import_module(f'.{serde}', __name__), fn)(llm, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\transformers\__init__.py", line 155, in get
    raise openllm.exceptions.OpenLLMException(f'Failed while getting stored artefact (lookup for traceback):\n{err}') from err
openllm_core.exceptions.OpenLLMException: Failed while getting stored artefact (lookup for traceback):
Model 'pt-tiiuae--falcon-7b:898df1396f35e447d5fe44e0a3ccaaaa69f30d36' is not found in BentoML store <osfs 'C:\Users\SNS\bentoml\models'>, you may need to run `bentoml models pull` first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\transformers\__init__.py", line 147, in get
    model = bentoml.models.get(llm.tag)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\simple_di\__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\bentoml\models.py", line 45, in get
    return _model_store.get(tag)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\bentoml\_internal\store.py", line 158, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'pt-tiiuae--falcon-7b:898df1396f35e447d5fe44e0a3ccaaaa69f30d36' is not found in BentoML store <osfs 'C:\Users\SNS\bentoml\models'>, you may need to run `bentoml models pull` first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\SNS\anaconda3\envs\ol\Scripts\openllm.exe\__main__.py", line 7, in <module>
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\entrypoint.py", line 196, in wrapper
    return_value = func(*args, **attrs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\entrypoint.py", line 178, in wrapper
    return f(*args, **attrs)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\_factory.py", line 179, in start_cmd
    llm = openllm.utils.infer_auto_class(env['backend_value']).for_model(model,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\models\auto\factory.py", line 52, in for_model
    if ensure_available: llm.save_pretrained()
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\_llm.py", line 672, in save_pretrained
    return openllm.import_model(self.config['start_name'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\_sdk.py", line 262, in _import_model
    return import_command.main(args=args, standalone_mode=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\entrypoint.py", line 196, in wrapper
    return_value = func(*args, **attrs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\entrypoint.py", line 178, in wrapper
    return f(*args, **attrs)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\cli\entrypoint.py", line 422, in import_command
    _ref = openllm.serialisation.get(llm, auto_import=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\__init__.py", line 75, in caller
    return getattr(importlib.import_module(f'.{serde}', __name__), fn)(llm, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\transformers\__init__.py", line 154, in get
    if auto_import: return import_model(llm, trust_remote_code=llm.trust_remote_code)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\simple_di\__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\openllm\serialisation\transformers\__init__.py", line 124, in import_model
    snapshot_download(llm.model_id, local_dir=bentomodel.path, local_dir_use_symlinks=False, ignore_patterns=HfIgnore.ignore_patterns(llm))
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 214, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\file_download.py", line 1431, in hf_hub_download
    http_get(
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\huggingface_hub\file_download.py", line 551, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "C:\Users\SNS\anaconda3\envs\ol\Lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading (…)l-00001-of-00002.bin:  10%|███▊                                    | 954M/9.95G [50:47<7:58:56, 313kB/s]

(ol) C:\Users\SNS>
----------------------------------------------------------------------------------------------------------------------------------------------
Whenever I try to run specific model id, it went into connection error or timeouts. What should I do? the "openllm start opt" did work well, but I do want to run specific model.

**Comment by parano** [comment]
Hi @latishab it may has to do with your environment - could you try running it from google colab environment here? https://colab.research.google.com/github/bentoml/OpenLLM/blob/main/examples/openllm-llama2-demo/openllm_llama2_demo.ipynb

**Comment by aarnphm** [comment]
Sorry, but this seems to be purely environment setup issue.
I can run falcon models successfully.

Feel free to reopen if there is a different issue arise.
