### ISSUE TITLE
AttributeError: module 'openllm_client' has no attribute 'GrpcClient'

### ISSUE THREAD

**Issue by hdnh2006** [bentoml/OpenLLM#603]
### Describe the bug

Hello! 

I am trying to deploy Llama2 locally. The servers seems to run good with the following command:
```
openllm start opt --quantize int4 --model-id meta-llama/Llama-2-7b-chat-hf --port 5000
``` 
But when I try to call the model with this code:
```
from langchain.llms import OpenLLM

llm = OpenLLM(server_url='http://0.0.0.0:5000', server_type='grpc')
llm("What is the difference between a duck and a goose? And why there are so many Goose in Canada?")
``` 

I get the following error:
```
Traceback (most recent call last):

  Cell In[1], line 3
    llm = OpenLLM(server_url='http://0.0.0.0:5000', server_type='grpc')

  File ~/.virtualenvs/openllm/lib/python3.10/site-packages/langchain/llms/openllm.py:150 in __init__
    else openllm.client.GrpcClient

  File ~/.virtualenvs/openllm/lib/python3.10/site-packages/openllm/client.py:23 in __getattr__
    return getattr(openllm_client, it)

AttributeError: module 'openllm_client' has no attribute 'GrpcClient'
```

I think it is a problem of versions or anything else but I don't know exactly what is happening. 

My version of openllm is:
```
openllm.__version__
Out[3]: '0.4.1'
```

Can you please help me to solve this?

### Environment

accelerate==0.24.1
aiohttp==3.8.6
aiosignal==1.3.1
anyio==4.0.0
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
bentoml==1.1.9
bitsandbytes==0.41.2.post2
build==1.0.3
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
coloredlogs==15.0.1
contextlib2==21.6.0
cuda-python==12.3.0
datasets==2.14.6
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
exceptiongroup==1.1.3
fastcore==1.5.29
filelock==3.13.1
filetype==1.2.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.10.0
ghapi==1.0.4
h11==0.14.0
httpcore==1.0.1
httpx==0.25.1
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
inflection==0.5.1
Jinja2==3.1.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
openllm==0.4.1
openllm-client==0.4.1
openllm-core==0.4.1
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.14.0
orjson==3.9.10
packaging==23.2
pandas==2.0.3
pathspec==0.11.2
Pillow==10.1.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
prometheus-client==0.18.0
protobuf==4.25.0
psutil==5.9.6
pyarrow==14.0.1
pydantic==1.10.13
Pygments==2.16.1
pyparsing==3.1.1
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
regex==2023.10.3
requests==2.31.0
rich==13.6.0
safetensors==0.4.0
schema==0.7.5
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.32.0.post1
sympy==1.12
tabulate==0.9.0
tokenizers==0.14.1
tomli==2.0.1
torch==2.1.0
tornado==6.3.3
tqdm==4.66.1
transformers==4.35.0
triton==2.1.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
uvicorn==0.24.0.post1
watchfiles==0.21.0
wcwidth==0.2.9
wrapt==1.16.0
xxhash==3.4.1
yarl==1.9.2
zipp==3.17.0

**Comment by aarnphm** [comment]
You start a HTTPServer, and I'm still in the progress of updating the gRPC client

Also continuous batching is only currently supported on HTTP, so I suggest to use HTTP instead.

**Comment by hdnh2006** [comment]
I don't get it. I am using normal http.

**Comment by gpresearch13** [comment]
I was having the same issue and now I get `AttributeError: 'HTTPClient' object has no attribute 'configuration'` using normal http.

**Comment by gpresearch13** [comment]
> I was having the same issue and now I get `AttributeError: 'HTTPClient' object has no attribute 'configuration'` using normal http.

I'm trying to submit a prompt to the model via python.  Is there a version of openllm I can roll back to that has this working?

**Comment by aarnphm** [comment]
I have a upstream langchain PR https://github.com/langchain-ai/langchain/pull/12968 to address this.

**Comment by aarnphm** [comment]
While it is not getting merged, you can install the patch with `pip install "git+https://github.com/bentoml/langchain.git@chore/migrate-to-new-api#subdirectory=libs/langchain"`

**Comment by gpresearch13** [comment]
This just gives me a new error

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/opt/conda/lib/python3.10/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 214, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

**Comment by gpresearch13** [comment]
Also getting this error:

`AttributeError module openllm has no attribute HTTPClient`

**Comment by aarnphm** [comment]
Not sure if you are installing openllm correctly, but it should also install openllm-client and openllm-core

**Comment by Manel-Hik** [comment]
Hi, 
where can I find in the documentation a guide to integrate grpc with  openllm?

**Comment by aarnphm** [comment]
I have disabled grpc for now. Is there a specific reason why you want to use gRPC?

Currently streaming is only supported with HTTP.
