### ISSUE TITLE
bug: Falcon Inference giving  "Response not completed" with vLLM backend

### ISSUE THREAD

**Issue by leoprem** [bentoml/OpenLLM#649]
### Describe the bug

I'm trying to run tiiuae/falcon-7b with vLLM backend with or without adapters.
It fails with a "Response not completed" error which is triggered after a Value Error as seen in the log.
The model works with Pytorch backend, this behaviour is only seen with vLLM.

Any way to solve this as vLLM backend can support Falcon

OpenLLM==0.4.0

### To reproduce

Steps to reproduce:

`openllm start falcon --model-id tiiuae/falcon-7b --adapter-id /path/to/adapter --backend vllm`

or 

`openllm start falcon --model-id tiiuae/falcon-7b  --backend vllm`

POST: http://0.0.0.0:3000/v1/completions

JSON:
```
{
  "prompt": "This is a test",
  "model": "tiiuae--falcon-7b",
  "max_tokens": 256,
  "temperature": 0.7,
  "logprobs": 1,
  "top_p": 0.43,
  "n": 1,
  "stream": false
}
```

### Logs

```shell
2023-11-14T12:22:26+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service:svc" can be accessed at http://localhost:3000/metrics.
2023-11-14T12:22:27+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO 11-14 12:22:31 llm_engine.py:72] Initializing an LLM engine with config: model='/home/username/serve_llm/bentoml/models/vllm-tiiuae--falcon-7b/898df1396f35e447d5fe44e0a3ccaaaa69f30d36', tokenizer='/home/username/serve_llm/bentoml/models/vllm-tiiuae--falcon-7b/898df1396f35e447d5fe44e0a3ccaaaa69f30d36', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
INFO 11-14 12:22:36 llm_engine.py:207] # GPU blocks: 465194, # CPU blocks: 32768
2023-11-14T12:22:38+0000 [ERROR] [runner:llm-falcon-runner:1] Exception in ASGI application
Traceback (most recent call last):
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/bentoml/_internal/server/http/traffic.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 596, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/bentoml/_internal/server/http/instruments.py", line 252, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/bentoml/_internal/server/http/access.py", line 126, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/bentoml/_internal/server/runner_app.py", line 356, in streamer
    async for p in payload:
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/bentoml/_internal/server/runner_app.py", line 214, in inner
    async for data in ret:
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/openllm/_runners.py", line 78, in generate_iterator
    sampling_params = self.config.model_construct_env(stop=list(stop_), temperature=temperature, top_p=top_p, **attrs).to_sampling_config()
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/openllm_core/_configuration.py", line 1459, in to_sampling_config
    return self.sampling_config.build()
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/openllm_core/_configuration.py", line 431, in build
    return vllm.SamplingParams(max_tokens=self.max_tokens,
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/vllm/sampling_params.py", line 122, in __init__
    self._verify_non_beam_search()
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/vllm/sampling_params.py", line 174, in _verify_non_beam_search
    raise ValueError("early_stopping is not effective and must be "
ValueError: early_stopping is not effective and must be False when not using beam search.
Traceback (most recent call last):
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/openllm/entrypoints/openai.py", line 269, in create_completions
    async for res in result_generator:
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/openllm/_llm.py", line 355, in generate_iterator
    async for out in self.runner.generate_iterator.async_stream(prompt_token_ids, request_id, stop, adapter_name, **config.model_dump(flatten=True)):
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 330, in async_stream_method
    async for b, end_of_http_chunk in resp.content.iter_chunks():
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 51, in __anext__
    rv = await self._stream.readchunk()
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 433, in readchunk
    await self._wait("readchunk")
  File "/home/username/serve_llm/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

### Environment

accelerate==0.24.1
aiohttp==3.8.6
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
bentoml==1.1.9
bitsandbytes==0.41.2.post2
build==1.0.3
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
cmake==3.27.7
coloredlogs==15.0.1
contextlib2==21.6.0
cuda-python==12.3.0
datasets==2.14.6
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
distro==1.8.0
docstring-parser==0.15
einops==0.7.0
exceptiongroup==1.1.3
fastapi==0.104.1
fastcore==1.5.29
filelock==3.13.1
filetype==1.2.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.10.0
ghapi==1.0.4
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.25.1
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
inflection==0.5.1
Jinja2==3.1.2
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
lit==17.0.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.1
ninja==1.11.1.1
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu11==10.9.0.58
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu11==10.2.10.91
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu11==11.7.4.91
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu11==2.14.3
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu11==11.7.91
nvidia-nvtx-cu12==12.1.105
openllm==0.4.0
openllm-client==0.4.0
openllm-core==0.4.0
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.14.0
orjson==3.9.10
packaging==23.2
pandas==2.0.3
pathspec==0.11.2
peft==0.6.2
Pillow==10.1.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
pkg_resources==0.0.0
pkgutil_resolve_name==1.3.10
prometheus-client==0.18.0
protobuf==4.25.0
psutil==5.9.6
pyarrow==14.0.1
pydantic==1.10.13
Pygments==2.16.1
pyparsing==3.1.1
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
ray==2.8.0
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
rich==13.6.0
rpds-py==0.12.0
safetensors==0.4.0
schema==0.7.5
scipy==1.10.1
sentencepiece==0.1.99
shtab==1.6.4
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tokenizers==0.14.1
tomli==2.0.1
torch==2.0.1
tornado==6.3.3
tqdm==4.66.1
transformers==4.35.0
triton==2.0.0
trl==0.7.4
typing_extensions==4.8.0
tyro==0.5.12
tzdata==2023.3
urllib3==2.1.0
uvicorn==0.24.0.post1
uvloop==0.19.0
vllm==0.2.1.post1
watchfiles==0.21.0
wcwidth==0.2.10
websockets==12.0
wrapt==1.16.0
xformers==0.0.22
xxhash==3.4.1
yarl==1.9.2
zipp==3.17.0

**Comment by aarnphm** [comment]
You can pass `early_stopping=False` to your request parameters.

**Comment by leoprem** [comment]
> You can pass `early_stopping=False` to your request parameters.

If you mean like this:
{```

  "prompt": "This is a test",
  "model": "tiiuae--falcon-7b",
  "max_tokens": 256,
  "temperature": 0.7,
  "logprobs": 1,
  "top_p": 0.43,
  "n": 1,
  "stream": false,
  "early_stopping":false
}
```
it doesn't work either unfortunately.  It gives the same response and logs.

I'm not sure if I'm missing something very obvious

**Comment by aarnphm** [comment]
Oh sorry, you are using openai compatible endpoint I assume?

**Comment by aarnphm** [comment]
I'm releasing 0.4.9 to address this problem.

**Comment by leoprem** [comment]
Yes thank you so much, looking forward to it.

**Comment by leoprem** [comment]
Thanks, Falcon is now working with vLLM  in openAI compatible endpoint.
Amazing work, the latency is really good.
