### ISSUE TITLE
bug: Failed to use Flan-T5 model

### ISSUE THREAD

**Issue by dzieciou** [bentoml/OpenLLM#650]
### Describe the bug

When trying to use Flan-T5 model I keep getting the following error:
```
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
```
I follow the instructions from your README

### To reproduce

In one terminal
```
virtualenv venv -p python3.9
source venv/bin/activate
pip install "openllm[flan-t5]"
openllm start google/flan-t5-large
```
In another terminal
```
source venv/bin/activate
export OPENLLM_ENDPOINT=http://localhost:3000
openllm query 'What are large language models?'
```

### Logs

```shell
vLLM is not available. Note that PyTorch backend is not as performant as vLLM and you should always consider using vLLM for production.
To disable these warnings, set 'OPENLLM_DISABLE_WARNING=True'
🚀Tip: run 'openllm build google/flan-t5-large --serialization safetensors' to create a BentoLLM for 'google/flan-t5-large'
2023-11-14T15:54:24+0100 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service:svc" can be accessed at http://localhost:3000/metrics.
2023-11-14T15:54:25+0100 [INFO] [cli] Starting production HTTP BentoServer from "_service:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
2023-11-14T15:54:53+0100 [INFO] [api_server:llm-flan-t5-service:14] 127.0.0.1:41378 (scheme=http,method=POST,path=/v1/metadata,type=application/json,length=2) (status=200,type=application/json,length=890) 1.641ms (trace=d7ec3a0e3bbe24d191ab86aa1ac6ba33,span=d98a00bc5bba1b98,sampled=1,service.name=llm-flan-t5-service)
2023-11-14T15:54:54+0100 [ERROR] [runner:llm-flan-t5-runner:1] Exception in ASGI application
Traceback (most recent call last):
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
return await self.app(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/applications.py", line 116, in __call__
await self.middleware_stack(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
raise exc
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
await self.app(scope, receive, _send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/http/traffic.py", line 26, in __call__
await self.app(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 596, in __call__
await self.app(scope, otel_receive, otel_send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/http/instruments.py", line 252, in __call__
await self.app(scope, receive, wrapped_send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/http/access.py", line 126, in __call__
await self.app(scope, receive, wrapped_send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
raise exc
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
await app(scope, receive, sender)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 746, in __call__
await route.handle(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
await self.app(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 75, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
raise exc
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
await app(scope, receive, sender)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
await response(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/responses.py", line 259, in __call__
await wrap(partial(self.listen_for_disconnect, receive))
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
raise exceptions[0]
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/responses.py", line 255, in wrap
await func()
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/responses.py", line 244, in stream_response
async for chunk in self.body_iterator:
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/runner_app.py", line 356, in streamer
async for p in payload:
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/runner_app.py", line 214, in inner
async for data in ret:
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/openllm/_runners.py", line 118, in generate_iterator
async for generation_output in self.forward(prompt_token_ids, request_id, stop=stop, **attrs):
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/openllm/_runners.py", line 148, in forward
out = self.model(torch.as_tensor([prompt_token_ids], device=self.model.device), use_cache=True)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1746, in forward
decoder_outputs = self.decoder(
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1011, in forward
raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
2023-11-14T15:54:54+0100 [ERROR] [api_server:llm-flan-t5-service:14] Exception in ASGI application
Traceback (most recent call last):
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
return await self.app(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/applications.py", line 116, in __call__
await self.middleware_stack(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
raise exc
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
await self.app(scope, receive, _send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/http/traffic.py", line 26, in __call__
await self.app(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/http/instruments.py", line 135, in __call__
await self.app(scope, receive, wrapped_send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 596, in __call__
await self.app(scope, otel_receive, otel_send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/server/http/access.py", line 126, in __call__
await self.app(scope, receive, wrapped_send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
raise exc
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
await app(scope, receive, sender)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 746, in __call__
await route.handle(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
await self.app(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 75, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
raise exc
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
await app(scope, receive, sender)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
await response(scope, receive, send)
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/responses.py", line 259, in __call__
await wrap(partial(self.listen_for_disconnect, receive))
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
raise exceptions[0]
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/responses.py", line 255, in wrap
await func()
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/starlette/responses.py", line 244, in stream_response
async for chunk in self.body_iterator:
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/openllm/_service.py", line 46, in generate_stream_v1
async for it in llm.generate_iterator(**llm_model_class(**input_dict).model_dump()):
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/openllm/_llm.py", line 554, in generate_iterator
async for out in self.runner.generate_iterator.async_stream(
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 330, in async_stream_method
async for b, end_of_http_chunk in resp.content.iter_chunks():
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 51, in __anext__
rv = await self._stream.readchunk()
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 433, in readchunk
await self._wait("readchunk")
File "/home/m.gawinecki/tmp/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.9
`python`: 3.9.16
`platform`: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
`uid_gid`: 1354815571:1354815571
<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.24.1
aiohttp==3.8.6
aiosignal==1.3.1
annotated-types==0.6.0
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
bentoml==1.1.9
bitsandbytes==0.41.2.post2
black==23.11.0
build==0.10.0
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
coloredlogs==15.0.1
contextlib2==21.6.0
cuda-python==12.3.0
dataclasses-json==0.6.2
datasets==2.14.6
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
distlib==0.3.7
distro==1.8.0
exceptiongroup==1.1.3
fairscale==0.4.13
fastcore==1.5.29
filelock==3.13.1
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.10.0
ghapi==1.0.4
greenlet==3.0.1
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
huggingface-hub==0.19.1
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
inflection==0.5.1
Jinja2==3.1.2
jsonpatch==1.33
jsonpointer==2.4
langchain==0.0.335
langsmith==0.0.64
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.20.1
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.2.1
numpy==1.26.2
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
openllm==0.4.6
openllm-client==0.4.6
openllm-core==0.4.6
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.14.0
orjson==3.9.10
packaging==23.2
pandas==2.1.3
pathspec==0.11.2
pip-requirements-parser==32.0.1
pip-tools==7.3.0
platformdirs==3.11.0
prometheus-client==0.18.0
psutil==5.9.6
pyarrow==14.0.1
pydantic==2.5.0
pydantic-core==2.14.1
Pygments==2.16.1
pyparsing==3.1.1
pyproject-hooks==1.0.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
regex==2023.10.3
requests==2.31.0
rich==13.6.0
safetensors==0.4.0
schema==0.7.5
scipy==1.11.3
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.23
starlette==0.32.0.post1
sympy==1.12
tenacity==8.2.3
tokenizers==0.14.1
tomli==2.0.1
torch==2.1.0
tornado==6.3.3
tqdm==4.66.1
transformers==4.35.0
triton==2.1.0
typing-extensions==4.8.0
typing-inspect==0.9.0
tzdata==2023.3
urllib3==2.1.0
uvicorn==0.24.0.post1
virtualenv==20.24.6
watchfiles==0.21.0
wrapt==1.16.0
xxhash==3.4.1
yarl==1.9.2
zipp==3.17.0
```

</details>

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.35.0
- Platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Huggingface_hub version: 0.19.1
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Don't know. Just following the steps from README
- Using distributed or parallel set-up in script?: Don't know. Just following the steps from README

**Comment by aarnphm** [comment]
I have now updated the main branch to bring back support for encoder-decoder models.

Will include this in 0.4.15
