### ISSUE TITLE
bug:  AttributeError: 'dict' object has no attribute 'schemas'

### ISSUE THREAD

**Issue by wuriyanto48** [bentoml/OpenLLM#688]
### Describe the bug

thank you for this amazing tools. just tried running what's in the documentation
```
openllm start facebook/opt-1.3b
```

### To reproduce

1.  install the latest openllm `pip install openllm`
2.  openllm start facebook/opt-1.3b

### Logs

```shell
ubuntu@ewd-pmtools:~$ openllm start facebook/opt-1.3b --port 9333
vLLM is not available. Note that PyTorch backend is not as performant as vLLM and you should always consider using vLLM for production.
To disable these warnings, set 'OPENLLM_DISABLE_WARNING=True'
Tip: run 'openllm build facebook/opt-1.3b --serialization legacy' to create a BentoLLM for 'facebook/opt-1.3b'
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml/__main__.py", line 4, in <module>
cli()
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml_cli/utils.py", line 362, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml_cli/utils.py", line 311, in wrapper
return func(*args, **kwargs)
return func(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml_cli/utils.py", line 290, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml_cli/env_manager.py", line 122, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml_cli/serve.py", line 260, in serve
serve_http_production(
File "/home/ubuntu/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml/serve.py", line 286, in serve_http_production
svc = load(bento_identifier, working_dir=working_dir)
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 374, in load
svc = import_service(
File "/home/ubuntu/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
module = importlib.import_module(module_name, package=working_dir)
File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 848, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/home/ubuntu/.local/lib/python3.8/site-packages/openllm/_service.py", line 94, in <module>
openllm.mount_entrypoints(svc, llm)
File "/home/ubuntu/.local/lib/python3.8/site-packages/openllm/entrypoints/__init__.py", line 11, in mount_entrypoints
svc = module.mount_to_svc(svc, llm)
File "/home/ubuntu/.local/lib/python3.8/sit
svc = module.mount_to_svc(svc, llm)
File "/home/ubuntu/.local/lib/python3.8/site-packages/openllm/entrypoints/openai.py", line 113, in mount_to_svc
return append_schemas(svc, schemas.get_schema(routes=app.routes, mount_path='/v1'))
File "/home/ubuntu/.local/lib/python3.8/site-packages/openllm/entrypoints/_openapi.py", line 610, in append_schemas
svc_schema = svc_schema.asdict()
File "/home/ubuntu/.local/lib/python3.8/site-packages/bentoml/_internal/service/openapi/specification.py", line 281, in asdict
return bentoml_cattr.unstructure(self)
File "/home/ubuntu/.local/lib/python3.8/site-packages/cattrs/converters.py", line 238, in unstructure
return self._unstructure_func.dispatch(
File "<cattrs generated unstructure bentoml._internal.service.openapi.specification.OpenAPISpecification>", line 11, in unstructure_OpenAPISpecificati
on
File "/home/ubuntu/.local/lib/python3.8/site-packages/cattrs/converters.py", line 960, in unstructure_optional
return None if val is None else _handler(val)
File "<cattrs generated unstructure bentoml._internal.service.openapi.specification.Components>", line 3, in unstructure_Components
AttributeError: 'dict' object has no attribute 'schemas'
```

### Environment

openllm, 0.4.12 (compiled: False)
Python (CPython) 3.8.10
Ubuntu 20.04.6 LTS

**Comment by aarnphm** [comment]
I'm fixing this and will be release in 0.4.14

**Comment by aarnphm** [comment]
https://github.com/bentoml/BentoML/issues/4290

**Comment by aarnphm** [comment]
This is now released. I have ignore cattrs version that breaks our validation logic

**Comment by wuriyanto48** [comment]
thank you @aarnphm , version 0.4.14 works fine
for those who experience the same issue

this will uninstall cattrs version  23.2.0
```
pip uninstall cattrs
```

and then upgrade the Openllm
```
pip install --upgrade openllm==0.4.14
```

**Comment by muc-martin** [comment]
Hi @aarnphm  this is still an issue for me in version 0.4.14.
I tried with a fresh install using `pip install --upgrade openllm==0.4.14` 

and got the same error trying:

`openllm start TheBloke/zephyr-7B-beta-AWQ --backend vllm --quantize awq`

**Comment by aarnphm** [comment]
I think I will need to create a release for bentoml. Let me do that

**Comment by aarnphm** [comment]
Hey there can u try again?

**Comment by muc-martin** [comment]
Hi @aarnphm ,
I did a `pip --force-reinstall` and then it worked. Thanks!
