### ISSUE TITLE
bug: AttributeError: can't set attribute 'eos_token'

### ISSUE THREAD

**Issue by lovivi** [bentoml/OpenLLM#736]
### Describe the bug

When I execute TRUST on the P40 card_ REMOTE_ CODE=True openllm start/NAS/user/songjie/software/llm/chatglm3-6b Unable to load properly (can build normally, whether it is pt or vllm, but will report an error whenever requested)

The error is as follows:

### To reproduce

card_ REMOTE_ CODE=True openllm start/NAS/user/songjie/software/llm/chatglm3-6b

### Logs

```shell
2023-11-27T18:22:06+0800 [ERROR] [runner:llm-chatglm-runner:1] Application startup failed. Exiting.


Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|█▍        | 1/7 [00:01<00:10,  1.81s/it]
Loading checkpoint shards:  29%|██▊       | 2/7 [00:03<00:09,  1.81s/it]
Loading checkpoint shards:  43%|████▎     | 3/7 [00:05<00:07,  1.79s/it]
Loading checkpoint shards:  57%|█████▋    | 4/7 [00:07<00:05,  1.75s/it]
Loading checkpoint shards:  71%|███████▏  | 5/7 [00:08<00:03,  1.75s/it]
Loading checkpoint shards:  86%|████████▌ | 6/7 [00:10<00:01,  1.71s/it]
Loading checkpoint shards: 100%|██████████| 7/7 [00:11<00:00,  1.45s/it]
Loading checkpoint shards: 100%|██████████| 7/7 [00:11<00:00,  1.63s/it]
2023-11-27T18:22:32+0800 [ERROR] [runner:llm-chatglm-runner:1] An exception occurred while instantiating runner 'llm-chatglm-runner', see details below:
2023-11-27T18:22:32+0800 [ERROR] [runner:llm-chatglm-runner:1] Traceback (most recent call last):
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
self._set_handle(LocalRunnerRef)
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
runner_handle = handle_class(self, *args, **kwargs)
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/openllm/_runners.py", line 172, in __init__
self.llm, self.config, self.model, self.tokenizer = llm, llm.config, llm.model, llm.tokenizer
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/openllm/_llm.py", line 326, in tokenizer
if self.__llm_tokenizer__ is None: self.__llm_tokenizer__ = openllm.serialisation.load_tokenizer(self, **self.llm_parameters[-1])
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 44, in load_tokenizer
tokenizer = AutoTokenizer.from_pretrained(
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 755, in from_pretrained
return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
return cls._from_pretrained(
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
tokenizer = cls(*init_inputs, **init_kwargs)
File "/NAS/user/songjie/.cache/huggingface/modules/transformers_modules/tokenization_chatglm.py", line 108, in __init__
super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces,
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 363, in __init__
super().__init__(**kwargs)
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1604, in __init__
super().__init__(**kwargs)
File "/NAS/user/songjie/.conda/envs/vllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 861, in __init__
setattr(self, key, value)
AttributeError: can't set attribute 'eos_token'
```

### Environment

Driver Version: 535.129.03      
cuda-python               12.3.0                   pypi_0    pypi
cudatoolkit               11.8.0               h6a678d5_0
python                    3.10.13              h955ad1f_0
openllm                   0.4.31                   pypi_0    pypi
openllm-client            0.4.31                   pypi_0    pypi
openllm-core              0.4.31                   pypi_0    pypi

vllm                                         0.2.2
torch                                        2.1.0

**Comment by waltcow** [comment]
run chatglm3-6b model with error log as follow

```
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/starlette/routing.py", line 705, in lifespan
async with self.lifespan_context(app) as maybe_state:
File "/root/miniconda3/envs/openllm/lib/python3.10/contextlib.py", line 199, in __aenter__
return await anext(self.gen)
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
on_startup()
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 317, in init_local
raise e
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
self._set_handle(LocalRunnerRef)
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
runner_handle = handle_class(self, *args, **kwargs)
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/_runners.py", line 172, in __init__
self.llm, self.config, self.model, self.tokenizer = llm, llm.config, llm.model, llm.tokenizer
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/_llm.py", line 326, in tokenizer
if self.__llm_tokenizer__ is None: self.__llm_tokenizer__ = openllm.serialisation.load_tokenizer(self, **self.llm_parameters[-1])
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 44, in load_tokenizer
tokenizer = AutoTokenizer.from_pretrained(
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 755, in from_pretrained
return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
return cls._from_pretrained(
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
tokenizer = cls(*init_inputs, **init_kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/tokenization_chatglm.py", line 108, in __init__
super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces,
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 363, in __init__
super().__init__(**kwargs)
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1604, in __init__
super().__init__(**kwargs)
File "/root/miniconda3/envs/openllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 861, in __init__
setattr(self, key, value)
AttributeError: can't set attribute 'eos_token'

2023-11-29T18:25:36+0800 [ERROR] [runner:llm-chatglm-runner:1] Application startup failed. Exiting.
```

**Comment by danerlt** [comment]
I have also encountered the same problem.

**Comment by bojiang** [comment]
close for openllm 0.6
