### ISSUE TITLE
bug: TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by rayjang27** [bentoml/OpenLLM#738]
### Describe the bug

when I run the command "openllm start eleutherai/gpt-neox-20b" (or any other model has the same error)

the error occured "TypeError: getattr(): attribute name must be string"
![Uploading image.png…]()

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/bin/openllm", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openllm_cli/entrypoint.py", line 204, in wrapper
    return_value = func(*args, **attrs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openllm_cli/entrypoint.py", line 183, in wrapper
    return f(*args, **attrs)
  File "/usr/local/lib/python3.9/dist-packages/openllm_cli/entrypoint.py", line 406, in start_command
    llm = openllm.LLM[t.Any, t.Any](
  File "/usr/lib/python3.9/typing.py", line 670, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openllm/_llm.py", line 180, in __init__
    quantise=getattr(self._Quantise, backend)(self, quantize),
TypeError: getattr(): attribute name must be string
```

### Environment

python3.9

**Comment by aarnphm** [comment]
Not sure how you run into this issue, I didn't see this behaviour on 3.9
