### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by peijunzhang** [bentoml/OpenLLM#741]
### Describe the bug

When I run "openllm start facebook/opt-1.3b", I got the following error:

... ...
 File "/opt/miniconda3/envs/ai/lib/python3.11/typing.py", line 1261, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/openllm/_llm.py", line 182, in __init__
    quantise=getattr(self._Quantise, backend)(self, quantize),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attribute name must be string, not 'NoneType'

### To reproduce

1. Run “openllm start facebook/opt-1.3“
2. Error:
It is recommended to specify the backend explicitly. Cascading backend might lead to unexpected behaviour.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ai/bin/openllm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/openllm_cli/entrypoint.py", line 204, in wrapper
    return_value = func(*args, **attrs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/openllm_cli/entrypoint.py", line 183, in wrapper
    return f(*args, **attrs)
           ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/openllm_cli/entrypoint.py", line 415, in start_command
    llm = openllm.LLM[t.Any, t.Any](
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/typing.py", line 1261, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ai/lib/python3.11/site-packages/openllm/_llm.py", line 182, in __init__
    quantise=getattr(self._Quantise, backend)(self, quantize),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attribute name must be string, not 'NoneType'

### Environment

transformers: 4.35.2
python: 3.11.4
Plantform: Ubuntu 20.04

**Comment by peijunzhang** [comment]
@aarnphm Is there any patches or ways to fix it temporarily? Thanks.
