### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. 

### ISSUE THREAD

**Issue by cay89** [bentoml/OpenLLM#746]
I've tried to run zephyr-7b-alpha in docker container via Docker Desktop on Windows 10. I get the following error, when the server starts:

> [ERROR] [runner:llm-mistral-runner:1] An exception occurred while instantiating runner 'llm-mistral-runner', see details below:
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Logs: 
```
config.json: 100%|██████████| 628/628 [00:00<00:00, 2.80MB/s]
tokenizer_config.json: 100%|██████████| 1.43k/1.43k [00:00<00:00, 10.9MB/s]
tokenizer.model: 100%|██████████| 493k/493k [00:00<00:00, 3.02MB/s]
tokenizer.json: 100%|██████████| 1.80M/1.80M [00:01<00:00, 1.41MB/s]
added_tokens.json: 100%|██████████| 42.0/42.0 [00:00<00:00, 316kB/s]
special_tokens_map.json: 100%|██████████| 168/168 [00:00<00:00, 1.36MB/s]
eval_results.json: 100%|██████████| 557/557 [00:00<00:00, 4.30MB/s]
all_results.json: 100%|██████████| 732/732 [00:00<00:00, 6.88MB/s]
generation_config.json: 100%|██████████| 111/111 [00:00<00:00, 883kB/s]
colab-demo.ipynb: 100%|██████████| 167k/167k [00:00<00:00, 938kB/s]
model-00008-of-00008.safetensors: 100%|██████████| 816M/816M [12:54<00:00, 1.05MB/s]
model.safetensors.index.json: 100%|██████████| 23.9k/23.9k [00:00<00:00, 146MB/s]B/s] 
pytorch_model.bin.index.json: 100%|██████████| 23.9k/23.9k [00:00<00:00, 78.1MB/s]/s]]
thumbnail.png: 100%|██████████| 510k/510k [00:02<00:00, 225kB/s]12:58<02:30, 2.41MB/s]
train_results.json: 100%|██████████| 195/195 [00:00<00:00, 894kB/s]58<02:51, 2.25MB/s]
trainer_state.json: 100%|██████████| 104k/104k [00:00<00:00, 342kB/s]<02:27, 2.39MB/s]
model-00003-of-00008.safetensors: 100%|██████████| 1.98G/1.98G [15:40<00:00, 2.11MB/s]
model-00002-of-00008.safetensors: 100%|██████████| 1.95G/1.95G [15:41<00:00, 2.07MB/s]
model-00007-of-00008.safetensors: 100%|██████████| 1.98G/1.98G [15:44<00:00, 2.10MB/s]
model-00005-of-00008.safetensors: 100%|██████████| 1.98G/1.98G [19:21<00:00, 1.70MB/s]
model-00001-of-00008.safetensors: 100%|██████████| 1.89G/1.89G [19:45<00:00, 1.59MB/s]
model-00006-of-00008.safetensors: 100%|██████████| 1.95G/1.95G [20:10<00:00, 1.61MB/s]
model-00004-of-00008.safetensors: 100%|██████████| 1.95G/1.95G [20:25<00:00, 1.59MB/s]
Fetching 23 files: 100%|██████████| 23/23 [20:28<00:00, 53.39s/it] 19<02:36, 2.52MB/s]
2023-12-03 14:55:51 🚀Tip: run 'openllm build HuggingFaceH4/zephyr-7b-alpha --backend vllm --serialization safetensors' to create a BentoLLM for 'HuggingFaceH4/zephyr-7b-alpha'
2023-12-03 14:55:54 2023-12-03T13:55:54+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "_service:svc" can be accessed at http://localhost:3000/metrics.
2023-12-03 14:55:54 2023-12-03T13:55:54+0000 [INFO] [cli] Starting production HTTP BentoServer from "_service:svc" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
2023-12-03 14:56:00 INFO 12-03 13:56:00 llm_engine.py:72] Initializing an LLM engine with config: model='/root/bentoml/models/vllm-huggingfaceh4--zephyr-7b-alpha/2ce2d025864af849b3e5029e2ec9d568eeda892d', tokenizer='/root/bentoml/models/vllm-huggingfaceh4--zephyr-7b-alpha/2ce2d025864af849b3e5029e2ec9d568eeda892d', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
2023-12-03 14:56:00 Traceback (most recent call last):
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/openllm/_runners.py", line 106, in __init__
2023-12-03 14:56:00 self.model = vllm.AsyncLLMEngine.from_engine_args(
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
2023-12-03 14:56:00 engine = cls(parallel_config.worker_use_ray,
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
2023-12-03 14:56:00 self.engine = self._init_engine(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 305, in _init_engine
2023-12-03 14:56:00 return engine_class(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 110, in __init__
2023-12-03 14:56:00 self._init_workers(distributed_init_method)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 142, in _init_workers
2023-12-03 14:56:00 self._run_workers(
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
2023-12-03 14:56:00 output = executor(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 60, in init_model
2023-12-03 14:56:00 torch.cuda.set_device(self.device)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 404, in set_device
2023-12-03 14:56:00 torch._C._cuda_setDevice(device)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
2023-12-03 14:56:00 2023-12-03T13:56:00+0000 [ERROR] [runner:llm-mistral-runner:1] An exception occurred while instantiating runner 'llm-mistral-runner', see details below:
2023-12-03 14:56:00 torch._C._cuda_init()
2023-12-03 14:56:00 RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-12-03 14:56:00 2023-12-03T13:56:00+0000 [ERROR] [runner:llm-mistral-runner:1] Traceback (most recent call last):
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/openllm/_runners.py", line 106, in __init__
2023-12-03 14:56:00 self.model = vllm.AsyncLLMEngine.from_engine_args(
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
2023-12-03 14:56:00 engine = cls(parallel_config.worker_use_ray,
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
2023-12-03 14:56:00 self.engine = self._init_engine(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 305, in _init_engine
2023-12-03 14:56:00 return engine_class(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 110, in __init__
2023-12-03 14:56:00 self._init_workers(distributed_init_method)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 142, in _init_workers
2023-12-03 14:56:00 self._run_workers(
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
2023-12-03 14:56:00 output = executor(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 60, in init_model
2023-12-03 14:56:00 torch.cuda.set_device(self.device)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 404, in set_device
2023-12-03 14:56:00 torch._C._cuda_setDevice(device)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
2023-12-03 14:56:00 torch._C._cuda_init()
2023-12-03 14:56:00 RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-12-03 14:56:00 
2023-12-03 14:56:00 The above exception was the direct cause of the following exception:
2023-12-03 14:56:00 
2023-12-03 14:56:00 Traceback (most recent call last):
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
2023-12-03 14:56:00 self._set_handle(LocalRunnerRef)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
2023-12-03 14:56:00 runner_handle = handle_class(self, *args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
2023-12-03 14:56:00 self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/openllm/_runners.py", line 118, in __init__
2023-12-03 14:56:00 raise openllm.exceptions.OpenLLMException(f'Failed to initialise vLLMEngine due to the following error:\n{err}') from err
2023-12-03 14:56:00 openllm_core.exceptions.OpenLLMException: Failed to initialise vLLMEngine due to the following error:
2023-12-03 14:56:00 Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-12-03 14:56:00 
2023-12-03 14:56:00 2023-12-03T13:56:00+0000 [ERROR] [runner:llm-mistral-runner:1] Traceback (most recent call last):
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/openllm/_runners.py", line 106, in __init__
2023-12-03 14:56:00 self.model = vllm.AsyncLLMEngine.from_engine_args(
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
2023-12-03 14:56:00 engine = cls(parallel_config.worker_use_ray,
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
2023-12-03 14:56:00 self.engine = self._init_engine(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 305, in _init_engine
2023-12-03 14:56:00 return engine_class(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 110, in __init__
2023-12-03 14:56:00 self._init_workers(distributed_init_method)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 142, in _init_workers
2023-12-03 14:56:00 self._run_workers(
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
2023-12-03 14:56:00 output = executor(*args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 60, in init_model
2023-12-03 14:56:00 torch.cuda.set_device(self.device)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 404, in set_device
2023-12-03 14:56:00 torch._C._cuda_setDevice(device)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
2023-12-03 14:56:00 torch._C._cuda_init()
2023-12-03 14:56:00 RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-12-03 14:56:00 
2023-12-03 14:56:00 The above exception was the direct cause of the following exception:
2023-12-03 14:56:00 
2023-12-03 14:56:00 Traceback (most recent call last):
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 677, in lifespan
2023-12-03 14:56:00 async with self.lifespan_context(app) as maybe_state:
2023-12-03 14:56:00 File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
2023-12-03 14:56:00 return await anext(self.gen)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
2023-12-03 14:56:00 on_startup()
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner.py", line 317, in init_local
2023-12-03 14:56:00 raise e
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
2023-12-03 14:56:00 self._set_handle(LocalRunnerRef)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
2023-12-03 14:56:00 runner_handle = handle_class(self, *args, **kwargs)
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
2023-12-03 14:56:00 self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
2023-12-03 14:56:00 File "/usr/local/lib/python3.10/dist-packages/openllm/_runners.py", line 118, in __init__
2023-12-03 14:56:00 raise openllm.exceptions.OpenLLMException(f'Failed to initialise vLLMEngine due to the following error:\n{err}') from err
2023-12-03 14:56:00 openllm_core.exceptions.OpenLLMException: Failed to initialise vLLMEngine due to the following error:
2023-12-03 14:56:00 Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-12-03 14:56:00 
2023-12-03 14:56:00 2023-12-03T13:56:00+0000 [ERROR] [runner:llm-mistral-runner:1] Application startup failed. Exiting.
```

Dockerfile:
```
FROM nvidia/cuda:12.3.0-runtime-ubuntu22.04

RUN apt-get update && apt-get install python3.11 python3.11-pip -y
RUN pip install "openllm[vllm]"

EXPOSE 3000

ENTRYPOINT openllm start HuggingFaceH4/zephyr-7b-alpha --backend vllm
```

When I'm run the `docker run --gpus all nvidia/cuda:12.3.0-base-ubuntu22.04 nvidia-smi` command on my host machine, then the vga seems to be visible from the container:

```
Unable to find image 'nvidia/cuda:12.3.0-base-ubuntu22.04' locally
12.3.0-base-ubuntu22.04: Pulling from nvidia/cuda
aece8493d397: Already exists
03bb9eb021f5: Already exists
d1937dd2edf2: Already exists
89aa5c6f8794: Already exists
7d4f0f8effa7: Already exists
Digest: sha256:ab701cbe9784a586949674dac46a83cd4bed19944fbc9324619317be865ea678
Status: Downloaded newer image for nvidia/cuda:12.3.0-base-ubuntu22.04
Sun Dec  3 13:34:01 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.04              Driver Version: 546.17       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070        On  | 00000000:01:00.0  On |                  N/A |
|  0%   52C    P8              24W / 220W |    966MiB /  8192MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

What am I doing wrong?

**Comment by cay89** [comment]
Ok, when I'm runned it from powershell with ` --gpus all` property (instead of  GUI), this error was gone, but heres another:

> ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

Is it possible that this model will not work with this VGA?

**Comment by cay89** [comment]
I'm trying, with this:

`ENTRYPOINT openllm start HuggingFaceH4/zephyr-7b-alpha --backend vllm --gpu-memory-utilization 0.5`

But it cause the following error:

> openllm_core.exceptions.OpenLLMException: Failed to initialise vLLMEngine due to the following error:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

Then:

> File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 109, in __init__
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 0 bytes is free. Process 481 has 17179869184.00 GiB memory in use. Of the allocated memory 12.74 GiB is allocated by PyTorch, and 13.52 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by cay89** [comment]
I've connected another RTX 3070 to my PC, and the memory issue has been resolved. However, a new problem has emerged, for which I am opening a new issue. I am closing this one since the original problem has been solved.

**Comment by queenvictoria** [comment]
> You can set --gpu-memory-utlization to 0.5

```bash
$ openllm start [model-name] --gpu_memory_utilization=0.5
```

**Comment by EntityinArray** [comment]
So, how to run this in Docker Desktop? Not via powershell?
