### ISSUE TITLE
bug: Response Payload not generated

### ISSUE THREAD

**Issue by seanbenhur** [bentoml/OpenLLM#777]
### Describe the bug

I am trying to host a flant5 model, after the flant5 model is hosted and when I try to send the request, I am getting the 500 error, saying Response payload is not completed

### To reproduce

`openllm start google/flan-t5-small  --port 3000 --do-not-track --api_workers 17`

### Logs

```shell
During handling of the above exception, another exception occurred:

+ Exception Group Traceback (most recent call last):
|   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
|     result = await app(  # type: ignore[func-returns-value]
|   File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
|     return await self.app(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
|     await self.middleware_stack(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
|     raise exc
|   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
|     await self.app(scope, receive, _send)
|   File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/server/http/traffic.py", line 23, in __call__
|     async with anyio.create_task_group():
|   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
|     raise BaseExceptionGroup(
| exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
+-+---------------- 1 ----------------
| Traceback (most recent call last):
|   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 259, in __call__
|     await wrap(partial(self.listen_for_disconnect, receive))
|   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
|     await func()
|   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 232, in listen_for_disconnect
|     message = await receive()
|   File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 634, in otel_receive
|     message = await receive()
|   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 538, in receive
|     await self.message_event.wait()
|   File "/opt/conda/lib/python3.10/asyncio/locks.py", line 214, in wait
|     await fut
| asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f4220549330
|
| During handling of the above exception, another exception occurred:
|
| Exception Group Traceback (most recent call last):
|   File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/server/http/traffic.py", line 26, in __call__
|     await self.app(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 596, in __call__
Traceback (most recent call last):
File "/opt/conda/lib/python3.10/site-packages/openllm/_llm.py", line 107, in generate_iterator
async for out in generator:
File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 330, in async_stream_method
async for b, end_of_http_chunk in resp.content.iter_chunks():
File "/opt/conda/lib/python3.10/site-packages/aiohttp/streams.py", line 60, in __anext__
rv = await self._stream.readchunk()
File "/opt/conda/lib/python3.10/site-packages/aiohttp/streams.py", line 431, in readchunk
await self._wait("readchunk")
File "/opt/conda/lib/python3.10/site-packages/aiohttp/streams.py", line 302, in _wait
await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/conda/lib/python3.10/site-packages/openllm/entrypoints/openai.py", line 203, in chat_completions
async for res in result_generator:
File "/opt/conda/lib/python3.10/site-packages/openllm/_llm.py", line 117, in generate_iterator
raise RuntimeError(f'Exception caught during generation: {err}') from err
RuntimeError: Exception caught during generation: Response payload is not completed
|     await self.app(scope, otel_receive, otel_send)
|   File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/server/http/instruments.py", line 252, in __call__
|     await self.app(scope, receive, wrapped_send)
|   File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/server/http/access.py", line 126, in __call__
|     await self.app(scope, receive, wrapped_send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
|     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
|     raise exc
|   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
|     await app(scope, receive, sender)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 754, in __call__
|     await self.middleware_stack(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 774, in app
|     await route.handle(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 296, in handle
|     await self.app(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
|     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
|     raise exc
|   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
|     await app(scope, receive, sender)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
|     await response(scope, receive, send)
|   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 252, in __call__
|     async with anyio.create_task_group() as task_group:
|   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
|     raise BaseExceptionGroup(
| exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
+-+---------------- 1 ----------------
| Traceback (most recent call last):
|   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
|     await func()
|   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 244, in stream_response
|     async for chunk in self.body_iterator:
|   File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/server/runner_app.py", line 356, in streamer
|     async for p in payload:
|   File "/opt/conda/lib/python3.10/site-packages/bentoml/_internal/server/runner_app.py", line 214, in inner
|     async for data in ret:
|   File "/opt/conda/lib/python3.10/site-packages/openllm/_runners.py", line 165, in generate_iterator
|     if config['logprobs'] > 0:  # FIXME: logprobs is not supported
| TypeError: '>' not supported between instances of 'NoneType' and 'int'
+------------------------------------
2023-12-14T06:29:09+0000 [ERROR] [api_server:llm-flan-t5-service:16] Error generating completion: Exception caught during generation: Response payload is not completed (trace=e4c9f6bf4f0ff411ce0bbba2ce514efb,span=8f14c5ff44dfa6f9,sampled=1,service.name=llm-flan-t5-service)
```

### Environment

bentoml==0.4.38

**Comment by aarnphm** [comment]
Thanks for spotting this, will release a patch soon.

**Comment by aarnphm** [comment]
releasing 0.4.39 for this thanks.

**Comment by seanbenhur** [comment]
hi, even with 0.4.39, I got the same error, then upgraded to 0.4.40 and I get a different error, which I posted[ here](https://github.com/bentoml/OpenLLM/issues/785)
