### ISSUE TITLE
bug: fail to start service in quickstarts

### ISSUE THREAD

**Issue by Epsilon314** [bentoml/OpenLLM#788]
### Describe the bug

Followed this [quickstart](https://docs.bentoml.org/en/latest/quickstarts/deploy-a-large-language-model-with-openllm-and-bentoml.html#), but encountered a typeError when trying to start the  service:
```
TypeError: __init__() missing 11 required keyword-only arguments: 'model_id', 'llm_config', 'quantization_config', '_quantize', '_model_version', '_tag', '_serialisation', '_local', '_prompt_template', '_system_message', and '_adapters_mapping'
```

### To reproduce

1. python3.8, bentoML & openllm installed
2. copy the service code from the [quickstart](https://docs.bentoml.org/en/latest/quickstarts/deploy-a-large-language-model-with-openllm-and-bentoml.html#) into service.py
3. create a bentofile
```yaml
service: 'service:svc'
include:
  - 'service.py'
python:
  packages:
    - openllm[vllm]
docker:
  cuda_version: "11.6.2"
```
4. bentoml build --containerize and run in docker
5. got the following error on start:
```
Traceback (most recent call last):
  File "/usr/local/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml_cli/utils.py", line 362, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml_cli/utils.py", line 333, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml_cli/utils.py", line 290, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml_cli/env_manager.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml_cli/serve.py", line 260, in serve
    serve_http_production(
  File "/usr/local/lib/python3.8/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.8/dist-packages/bentoml/serve.py", line 286, in serve_http_production
    svc = load(bento_identifier, working_dir=working_dir)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/service/loader.py", line 336, in load
    svc = load_bento_dir(bento_path, standalone_load=standalone_load)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/service/loader.py", line 236, in load_bento_dir
    return _load_bento(bento, standalone_load)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/service/loader.py", line 254, in _load_bento
    svc = import_service(
  File "/usr/local/lib/python3.8/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/service/loader.py", line 137, in import_service
    module = importlib.import_module(module_name, package=working_dir)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bentoml/bento/src/service.py", line 9, in <module>
    llm = LLM[Any, Any]("HuggingFaceH4/zephyr-7b-alpha", backend="vllm")
  File "/usr/lib/python3.8/typing.py", line 729, in __call__
    result = self.__origin__(*args, **kwargs)
TypeError: __init__() missing 11 required keyword-only arguments: 'model_id', 'llm_config', 'quantization_config', '_quantize', '_model_version', '_tag', '_serialisation', '_local', '_prompt_template', '_system_message', and '_adapters_mapping'
```

### Environment

bentoml@bento-75bbdd888c-g8mg8:~/bento$ bentoml env
#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.8
`python`: 3.8.10
`platform`: Linux-5.4.210-4-velinux1-amd64-x86_64-with-glibc2.29
`uid_gid`: 1034:1034
<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.24.1
aiohttp==3.8.6
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
bentoml==1.1.8
bitsandbytes==0.41.1
build==1.0.3
cattrs==23.1.2
certifi==2023.7.22
chardet==3.0.4
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
cmake==3.27.7
coloredlogs==15.0.1
contextlib2==21.6.0
cuda-python==12.3.0
datasets==2.14.6
dbus-python==1.2.16
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
exceptiongroup==1.1.3
fastapi==0.104.1
fastcore==1.5.29
filelock==3.13.1
filetype==1.2.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.10.0
ghapi==1.0.4
h11==0.14.0
httpcore==1.0.1
httptools==0.6.1
httpx==0.25.1
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.0
inflection==0.5.1
Jinja2==3.1.2
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
lit==17.0.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.1
ninja==1.11.1.1
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
openllm==0.3.14
openllm-client==0.3.14
openllm-core==0.3.14
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.13.3
orjson==3.9.10
packaging==23.2
pandas==2.0.3
pathspec==0.11.2
Pillow==10.1.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
pkgutil_resolve_name==1.3.10
prometheus-client==0.18.0
protobuf==4.25.0
psutil==5.9.6
pyarrow==14.0.0
pydantic==1.10.13
Pygments==2.16.1
PyGObject==3.36.0
pynvml==11.5.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
ray==2.8.0
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
requests-unixsocket==0.2.0
rich==13.6.0
rpds-py==0.12.0
safetensors==0.4.0
schema==0.7.5
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tokenizers==0.14.1
tomli==2.0.1
torch==2.0.1
tornado==6.3.3
tqdm==4.66.1
transformers==4.34.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
uvicorn==0.24.0
uvloop==0.19.0
vllm==0.2.1.post1
watchfiles==0.21.0
wcwidth==0.2.9
websockets==12.0
wrapt==1.15.0
xformers==0.0.22
xxhash==3.4.1
yarl==1.9.2
zipp==3.17.0
```

</details>

bentoml@bento-75bbdd888c-g8mg8:~/bento$ transformers-cli env

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.34.1
- Platform: Linux-5.4.210-4-velinux1-amd64-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by aarnphm** [comment]
Hi @Epsilon314 sorry for the late response. https://github.com/bentoml/BentoML/pull/4393 should update the service correctly.

This has to do with eager type evaluation in python 3.8. It shouldn't effect running code at all, so I have updated accordingly. Thanks for reporting this.
