### ISSUE TITLE
bug: 'torch.dtype' object has no attribute 'lower'

### ISSUE THREAD

**Issue by seanbenhur** [bentoml/OpenLLM#835]
### Describe the bug

I am trying to host Mistral with a LoRA adapter on a GPU, when I tried to start the openllm server using 

`openllm mistral --serialization safetensors --backend vllm --quantize int4 --adapter-id /path/to/adapter:local_adapter `

The server starts, after that, I am getting this error

```

Traceback (most recent call last):
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/starlette/routing.py", line 705, in lifespan
async with self.lifespan_context(app) as maybe_state:
File "/opt/conda/envs/pytorch/lib/python3.10/contextlib.py", line 199, in __aenter__
return await anext(self.gen)
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bentoml/_internal/server/base_app.py", line 75, in lifespan
on_startup()
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 317, in init_local
raise e
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 307, in init_local
self._set_handle(LocalRunnerRef)
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 150, in _set_handle
runner_handle = handle_class(self, *args, **kwargs)
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 27, in __init__
self._runnable = runner.runnable_class(**runner.runnable_init_params)  # type: ignore
File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/openllm/_runners.py", line 148, in __init__
raise openllm.exceptions.OpenLLMException(f'Failed to initialise vLLMEngine due to the following error:\n{err}') from err
openllm_core.exceptions.OpenLLMException: Failed to initialise vLLMEngine due to the following error:
'torch.dtype' object has no attribute 'lower'
```

I tried without the quantization method as well, but i got the same error

### To reproduce

`openllm mistral --serialization safetensors --backend vllm --quantize int4 --adapter-id /path/to/adapter:local_adapter `

### Environment

`bentoml`: 1.1.11
`python`: 3.10.11
`platform`: Linux-5.15.0-1036-aws-x86_64-with-glibc2.31
`uid_gid`: 1000:1000
`conda`: 22.11.1
`in_conda_env`: True

I am using openllm 0.4.41

### System information (Optional)

GPU: A10g(g5.xlarge)

**Comment by bojiang** [comment]
close for openllm 0.6
