### ISSUE TITLE
bug: Inference fails for `docker run` with `google/flan-t5-large` model with `pytorch` on CPU

### ISSUE THREAD

**Issue by cryoff** [bentoml/OpenLLM#840]
### Describe the bug

The following `docker run` command starts the service, shows the available models but fails to run the completion:

```
docker run --rm -it -p 3000:3000 ghcr.io/bentoml/openllm start google/flan-t5-large --backend pt
```

The following request to `completion` endpoint 

```
curl -X 'POST' \
  'http://localhost:3000/v1/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt": "This is a test",
  "model": "google--flan-t5-large",
  "max_tokens": 256,
  "temperature": 0.7,
  "logprobs": 1,
  "top_p": 0.43,
  "n": 1,
  "stream": false
}'
```

is failing with
```
2024-01-09T17:49:00+0000 [INFO] [runner:llm-flan-t5-runner:1] _ (scheme=http,method=POST,path=/generate_iterator,type=application/octet-stream,length=1761) (status=200,type=application/vnd.bentoml.stream_outputs,length=) 1613.149ms (trace=7893daab29524d27ea900420ae695e51,span=45c76ea5db8294b4,sampled=1,service.name=llm-flan-t5-runner)

Traceback (most recent call last):
File "/openllm-python/src/openllm/entrypoints/openai.py", line 388, in completions
logprobs = create_logprobs(token_ids, top_logprobs, request.logprobs, llm=llm)
File "/openllm-python/src/openllm/entrypoints/openai.py", line 85, in create_logprobs
step_top_logprobs = top_logprobs[i]
TypeError: 'NoneType' object is not subscriptable
2024-01-09T17:49:00+0000 [ERROR] [api_server:llm-flan-t5-service:2] Error generating completion: 'NoneType' object is not subscriptable (trace=7893daab29524d27ea900420ae695e51,span=4234e443e6a08778,sampled=1,service.name=llm-flan-t5-service)
```

### Environment

docker image: ghcr.io/bentoml/openllm

docker image inspect:
```
"Id": "sha256:24c4c419d1c36daf8d8469c8c0cc1f5b75e9326a7870a699ba1d2e53ae867ad2",
        "RepoTags": [
            "ghcr.io/bentoml/openllm:latest"
        ],
        "RepoDigests": [
            "ghcr.io/bentoml/openllm@sha256:eaad3b8bd66d15af07f7af6d4e72fef30f59dea15705cf840c3ee1d392cbeed7"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-12-18T17:41:50.749720532Z",
...
```

### System information (Optional)

ram: 32GB
processor: Intel i5
os: Ubuntu 20.04.6 LTS

**Comment by wuxmax** [comment]
i encounter the same problem with the "mistralai/Mistral-7B-Instruct-v0.2" model
