### ISSUE TITLE
bug: "Failed to parse JSON from SSE message" error

### ISSUE THREAD

**Issue by cogyair** [bentoml/OpenLLM#864]
### Describe the bug

the error I get:

2024-01-25T14:13:51+0000 [ERROR] [api_server:2] Error generating completion: Exception caught during generation: Failed to parse JSON from SSE message: '{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank","token_ids":[10449],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank you","token_ids":[10449,345],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank you for","token_ids":[10449,345,329],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank you for your","token_ids":[10449,345,329,534],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank you for your service","token_ids":[10449,345,329,534,2139],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank you for your service.<","token_ids":[10449,345,329,534,2139,29847],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Thank you for your service.<|","token_ids":[10449,345,329,534,2139,29847,91

### To reproduce

Upgraded python to 3.9
machine with no GPU (don't seem to be related)
pip install bentoml scikit-learn pandas
pip install openllm
DTYPE=float32 TRUST_REMOTE_CODE=True openllm start microsoft/phi-1_5
check that you can call the model   using curl
curl -X 'POST' \
    'http://0.0.0.0:3000/v1/generate' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{"prompt": "What are Large Language Models?"}'

Works!

build a bento out of this model: 
openllm build phi --model-id microsoft/phi-1_5 --backend pt --overwrite

run : (the generated file is from the bento the openllm command created)
TRUST_REMOTE_CODE=True DTYPE=float32 bentoml serve generated_phi_service.py

check it with the above curl  -works!!

containerize:
bentoml containerize microsoft--phi-1-5-service:latest -t phi:latest --opt progress=plain

run it:
docker run --rm -p 3000:3000 --env DTYPE=float32 --env TRUST_REMOTE_CODE=True phi:latest

try it with the same curl - get the above error

### Logs

```shell
root@bentotest:~/bentoml/bentos/microsoft--phi-1-5-service/83b9c526374a136c8d808fd55bdb15ae351584fc/src# docker run --rm -p 3000:3000 --env DTYPE=float32 --env TRUST_REMOTE_CODE=True phi:latest

2024-01-25T14:11:57+0000 [INFO] [cli] Service loaded from Bento directory: bentoml.Service(tag="microsoft--phi-1-5-service:83b9c526374a136c8d808fd55bdb15ae351584fc", path="/home/bentoml/bento/")
2024-01-25T14:11:57+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "/home/bentoml/bento" can be accessed at http://localhost:3000/metrics.
2024-01-25T14:11:58+0000 [INFO] [cli] Starting production HTTP BentoServer from "/home/bentoml/bento" listening on http://0.0.0.0:3000 (Press CTRL+C to quit)
2024-01-25T14:12:05+0000 [INFO] [api_server:1] Service loaded from Bento directory: bentoml.Service(tag="microsoft--phi-1-5-service:83b9c526374a136c8d808fd55bdb15ae351584fc", path="/home/bentoml/bento/")
2024-01-25T14:12:05+0000 [INFO] [api_server:2] Service loaded from Bento directory: bentoml.Service(tag="microsoft--phi-1-5-service:83b9c526374a136c8d808fd55bdb15ae351584fc", path="/home/bentoml/bento/")
2024-01-25T14:12:05+0000 [INFO] [api_server:3] Service loaded from Bento directory: bentoml.Service(tag="microsoft--phi-1-5-service:83b9c526374a136c8d808fd55bdb15ae351584fc", path="/home/bentoml/bento/")
2024-01-25T14:12:05+0000 [INFO] [runner:llm-phi-runner:1] Service loaded from Bento directory: bentoml.Service(tag="microsoft--phi-1-5-service:83b9c526374a136c8d808fd55bdb15ae351584fc", path="/home/bentoml/bento/")
2024-01-25T14:12:05+0000 [INFO] [api_server:4] Service loaded from Bento directory: bentoml.Service(tag="microsoft--phi-1-5-service:83b9c526374a136c8d808fd55bdb15ae351584fc", path="/home/bentoml/bento/")
/usr/local/lib/python3.11/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

No chat template is defined for this tokenizer - using a default chat template that implements the ChatML format (without BOS/EOS tokens!). If the default is not appropriate for your model, please set `tokenizer.chat_template` to an appropriate template. See https://huggingface.co/docs/transformers/main/chat_templating for more information.

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/openllm_core/_schemas.py", line 165, in from_runner
    structured = orjson.loads(data)
                 ^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected content after document: line 1 column 458 (char 457)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/openllm/_llm.py", line 116, in generate_iterator
    generated = GenerationOutput.from_runner(out).with_options(prompt=prompt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openllm_core/_schemas.py", line 167, in from_runner
    raise ValueError(f'Failed to parse JSON from SSE message: {data!r}') from e
ValueError: Failed to parse JSON from SSE message: '{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did","token_ids":[11633],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you","token_ids":[11633,345],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear","token_ids":[11633,345,3285],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about","token_ids":[11633,345,3285,546],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the","token_ids":[11633,345,3285,546,262],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the little","token_ids":[11633,345,3285,546,262,1310],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the little girl","token_ids":[11633,345,3285,546,262,1310,2576],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the little girl who","token_ids":[11633,345,3285,546,262,1310,2576,508],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the little girl who cried","token_ids":[11633,345,3285,546,262,1310,2576,508,16896],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"pro
...
...
7,351,6041,286,40005,1326,11,18662,11,290,477,2676,341,13,17641,703,262,2456,287,262,886,286,262,3951,2128,2092,290,2128,588,366,18829,526,1867,1611,286,1245,857,262,3912,286,262,2456],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/openllm/entrypoints/openai.py", line 224, in chat_completions
    async for res in result_generator:
  File "/usr/local/lib/python3.11/dist-packages/openllm/_llm.py", line 125, in generate_iterator
    raise RuntimeError(f'Exception caught during generation: {err}') from err
RuntimeError: Exception caught during generation: Failed to parse JSON from SSE message: '{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did","token_ids":[11633],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you","token_ids":[11633,345],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear","token_ids":[11633,345,3285],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about","token_ids":[11633,345,3285,546],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the","token_ids":[11633,345,3285,546,262],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-cbfb8f1b30a4499a93fa4f63da17c287"}{"prompt":"","finished":false,"outputs":[{"index":0,"text":"Did you hear about the little","token_ids":[11633,345,3285,546,262,1310],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":

...
...
null,"finish_reason":null}],"prompt_token_ids":[27,91,320,62,9688,91,29,10057,198,1639,389,257,7613,8796,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,7220,198,24446,502,257,9707,29847,91,320,62,437,91,29,198,27,91,320,62,9688,91,29,562,10167,198],"prompt_logprobs":null,"request_id":"chatcmpl-2da2f8fcc8ec46ad9ca46811092631d5"}'
2024-01-25T14:13:51+0000 [INFO] [api_server:2] 172.17.0.1:52914 (scheme=http,method=POST,path=/v1/chat/completions,type=application/json,length=156) (status=500,type=application/json,length=68919) 55313.560ms (trace=972f6f489a69a7e82d051ab696c48fc6,span=4bf544ca19d78341,sampled=1,service.name=llm-phi-service)
```

### Environment

root@bentotest:~/bentoml/bentos/microsoft--phi-1-5-service/83b9c526374a136c8d808fd55bdb15ae351584fc/src# bentoml env
#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.11
`python`: 3.8.10
`platform`: Linux-5.15.0-1048-gcp-x86_64-with-glibc2.29
`uid_gid`: 0:0
<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.26.1
aiohttp==3.9.1
aioprometheus==23.12.0
aiosignal==1.3.1
anyio==4.2.0
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.2.0
Automat==0.8.0
bentoml==1.1.11
bitsandbytes==0.41.3.post2
blinker==1.4
build==0.10.0
cattrs==23.1.2
certifi==2019.11.28
chardet==3.0.4
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloud-init==23.3.3
cloudpickle==3.0.0
colorama==0.4.3
coloredlogs==15.0.1
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contextlib2==21.6.0
cryptography==2.8
cuda-python==12.3.0
datasets==2.16.1
dbus-python==1.2.16
deepmerge==1.1.1
Deprecated==1.2.14
dill==0.3.7
distlib==0.3.8
distro==1.9.0
distro-info==0.23+ubuntu1.1
einops==0.7.0
entrypoints==0.3
exceptiongroup==1.2.0
fastapi==0.109.0
fastcore==1.5.29
filelock==3.13.1
frozenlist==1.4.1
fs==2.4.16
fsspec==2023.12.2
ghapi==1.0.4
grpcio==1.60.0
h11==0.14.0
httpcore==1.0.2
httplib2==0.14.0
httpx==0.26.0
huggingface-hub==0.20.2
humanfriendly==10.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==6.11.0
incremental==16.10.1
inflection==0.5.1
Jinja2==3.1.3
joblib==1.3.2
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
more-itertools==4.2.0
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
netifaces==0.10.4
networkx==3.1
ninja==1.11.1.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.1.0
openai==1.9.0
openllm==0.4.41
openllm-client==0.4.41
openllm-core==0.4.41
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.16.1
orjson==3.9.10
packaging==23.2
pandas==2.0.3
pathspec==0.12.1
pexpect==4.6.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
platformdirs==4.1.0
prometheus-client==0.19.0
protobuf==4.25.2
psutil==5.9.7
pyarrow==14.0.2
pyarrow-hotfix==0.6
pyasn1==0.4.2
pyasn1-modules==0.2.1
pydantic==1.10.13
Pygments==2.17.2
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-debian==0.1.36+ubuntu1.1
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==5.3.1
pyzmq==25.1.2
quantile-python==1.1
ray==2.6.0
regex==2023.12.25
requests==2.22.0
requests-unixsocket==0.2.0
rich==13.7.0
safetensors==0.4.1
schema==0.7.5
scikit-learn==1.3.2
scipy==1.10.1
SecretStorage==2.3.1
sentencepiece==0.1.99
service-identity==18.1.0
simple-di==0.1.5
simplejson==3.16.0
six==1.14.0
sniffio==1.3.0
sos==4.5.6
ssh-import-id==5.10
starlette==0.35.1
sympy==1.12
systemd-python==234
threadpoolctl==3.2.0
tokenizers==0.15.0
tomli==2.0.1
torch==2.1.2
tornado==6.4
tqdm==4.66.1
transformers==4.36.2
triton==2.1.0
Twisted==18.9.0
typing_extensions==4.9.0
tzdata==2023.4
ubuntu-advantage-tools==8001
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
uvicorn==0.25.0
virtualenv==20.25.0
vllm==0.2.6
wadllib==1.3.3
watchfiles==0.21.0
wrapt==1.16.0
xformers==0.0.23.post1
xxhash==3.4.1
yarl==1.9.4
zipp==1.0.0
zope.interface==4.7.1
```

</details>

root@bentotest:~/bentoml/bentos/microsoft--phi-1-5-service/83b9c526374a136c8d808fd55bdb15ae351584fc/src# transformers-cli env

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.36.2
- Platform: Linux-5.15.0-1048-gcp-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: 0.26.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by cogyair** [comment]
I suspect that generate_iterator function consumed by :self.runner.generate_iterator.async_stream in _llm.py assumes the stream brings one message at a time while it can send a chunk of them.
maybe it is a timing issue that happens only when the bento is in a docker. 
just a guess..

**Comment by whyiug** [comment]
I had the same problem.

**Comment by cogyair** [comment]
what did you do to resolve? (I moved out of openllm for now..)

**Comment by meanwo** [comment]
I also had the same problem.
