### ISSUE TITLE
bug: Can't load local models with (No such file or directory) error

### ISSUE THREAD

**Issue by hahmad2008** [bentoml/OpenLLM#894]
### Describe the bug

I tried to use a mistral model which is saved at my machine locally. So when I tried all the following tried, I still get this error:

`FileNotFoundError: [Errno 2] No such file or directory: b'/root/bentoml/models/vllm-mistral--garrulus/latest'`

commands I tried:

- `OPENLLM_USE_LOCAL_LATEST=True  HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1  openllm start mistral --model-id mistral/garrulus/`

- `openllm start  mistral/garrulus/`

- ` openllm start mistral --model-id  mistral/garrulus/`

- `openllm start mistral/garrulus  --dtype float16  --device all`

- **Error**:

````
It is recommended to specify the backend explicitly. Cascading backend might lead to unexpected behaviour.
Given model is a local model, OpenLLM will load model into memory for serialisation.
Loading checkpoint shards:   0%|                                                                                                                                                                    | 0/2 [00:00<?, ?it/s]/opt/conda/envs/openllm-env/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.31s/it]
🚀Tip: run 'openllm build mistral/garrulus --backend vllm --serialization legacy' to create a BentoLLM for 'mistral/garrulus'
Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/osfs.py", line 647, in open
return io.open(
^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: b'/root/bentoml/models/vllm-mistral--garrulus/latest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 144, in get
_tag.version = self._fs.readtext(_tag.latest_path())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/base.py", line 693, in readtext
self.open(
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/osfs.py", line 643, in open
with convert_os_errors("open", path):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/error_tools.py", line 89, in __exit__
reraise(fserror, fserror(self._path, exc=exc_value), traceback)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/six.py", line 718, in reraise
raise value.with_traceback(tb)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/osfs.py", line 647, in open
return io.open(
^^^^^^^^
fs.errors.ResourceNotFound: resource 'vllm-mistral--garrulus/latest' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 118, in _recreate_latest
items = self.list(tag.name)
^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 95, in list
raise NotFound(
bentoml.exceptions.NotFound: no Models with name 'vllm-mistral--garrulus' found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 223, in __init__
model = bentoml.models.get(self.tag)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/simple_di/__init__.py", line 139, in _
return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/models.py", line 45, in get
return _model_store.get(tag)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 149, in get
self._recreate_latest(_tag)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 120, in _recreate_latest
raise NotFound(
bentoml.exceptions.NotFound: no Models with name 'vllm-mistral--garrulus' exist in BentoML store <osfs '/root/bentoml/models'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/osfs.py", line 647, in open
return io.open(
^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: b'/root/bentoml/models/vllm-mistral--garrulus/latest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 144, in get
_tag.version = self._fs.readtext(_tag.latest_path())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/base.py", line 693, in readtext
self.open(
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/osfs.py", line 643, in open
with convert_os_errors("open", path):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/error_tools.py", line 89, in __exit__
reraise(fserror, fserror(self._path, exc=exc_value), traceback)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/six.py", line 718, in reraise
raise value.with_traceback(tb)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/fs/osfs.py", line 647, in open
return io.open(
^^^^^^^^
fs.errors.ResourceNotFound: resource 'vllm-mistral--garrulus/latest' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 118, in _recreate_latest
items = self.list(tag.name)
^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 95, in list
raise NotFound(
bentoml.exceptions.NotFound: no Models with name 'vllm-mistral--garrulus' found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/serialisation/transformers/__init__.py", line 68, in get
model = bentoml.models.get(llm.tag)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/simple_di/__init__.py", line 139, in _
return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/models.py", line 45, in get
return _model_store.get(tag)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 149, in get
self._recreate_latest(_tag)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/store.py", line 120, in _recreate_latest
raise NotFound(
bentoml.exceptions.NotFound: no Models with name 'vllm-mistral--garrulus' exist in BentoML store <osfs '/root/bentoml/models'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 276, in _torch_dtype
hf_config = transformers.AutoConfig.from_pretrained(self.bentomodel.path, trust_remote_code=self.trust_remote_code)
^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 365, in bentomodel
return openllm.serialisation.get(self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/serialisation/__init__.py", line 63, in caller
return getattr(importlib.import_module(f'.{serde}', 'openllm.serialisation'), fn)(llm, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/serialisation/transformers/__init__.py", line 79, in get
raise OpenLLMException(f'Failed while getting stored artefact (lookup for traceback):\n{err}') from err
openllm_core.exceptions.OpenLLMException: Failed while getting stored artefact (lookup for traceback):
no Models with name 'vllm-mistral--garrulus' exist in BentoML store <osfs '/root/bentoml/models'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
response.raise_for_status()
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mistral/garrulus/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/transformers/utils/hub.py", line 385, in cached_file
resolved_file = hf_hub_download(
^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1368, in hf_hub_download
raise head_call_error
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1238, in hf_hub_download
metadata = get_hf_file_metadata(
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
r = _request_wrapper(
^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
response = _request_wrapper(
^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 409, in _request_wrapper
hf_raise_for_status(response)
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 323, in hf_raise_for_status
raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-65c545e1-3314bd066dcc947a02d8e2a9;24fc44fe-fadf-4ffe-86ba-3e5fcc9369b2)

Repository Not Found for url: https://huggingface.co/mistral/garrulus/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/__main__.py", line 4, in <module>
cli()
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml_cli/utils.py", line 362, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml_cli/utils.py", line 311, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml_cli/utils.py", line 290, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml_cli/env_manager.py", line 122, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml_cli/serve.py", line 260, in serve
serve_http_production(
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/simple_di/__init__.py", line 139, in _
return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/serve.py", line 286, in serve_http_production
svc = load(bento_identifier, working_dir=working_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/service/loader.py", line 374, in load
svc = import_service(
^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/simple_di/__init__.py", line 139, in _
return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
module = importlib.import_module(module_name, package=working_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_service.py", line 8, in <module>
llm = openllm.LLM[t.Any, t.Any](
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/typing.py", line 1275, in __call__
result = self.__origin__(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 225, in __init__
model = openllm.serialisation.import_model(self, trust_remote_code=self.trust_remote_code)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/serialisation/__init__.py", line 63, in caller
return getattr(importlib.import_module(f'.{serde}', 'openllm.serialisation'), fn)(llm, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/serialisation/transformers/__init__.py", line 20, in import_model
(_base_decls, _base_attrs), tokenizer_attrs = llm.llm_parameters
^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 398, in llm_parameters
return (self._model_decls, self._model_attrs), self._tokenizer_attrs
^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 296, in _model_attrs
return {**self.import_kwargs[0], **self.__model_attrs}
^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 342, in import_kwargs
return {'device_map': 'auto' if self._has_gpus else None, 'torch_dtype': self._torch_dtype}, {'padding_side': 'left', 'truncation_side': 'left'}
^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/openllm/_llm.py", line 278, in _torch_dtype
hf_config = transformers.AutoConfig.from_pretrained(self.model_id, trust_remote_code=self.trust_remote_code)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1100, in from_pretrained
config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
resolved_config_file = cached_file(
^^^^^^^^^^^^
File "/opt/conda/envs/openllm-env/lib/python3.11/site-packages/transformers/utils/hub.py", line 406, in cached_file
raise EnvironmentError(
OSError: mistral/garrulus is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>
```

### To reproduce

I tried to use a mistral model which is saved at my machine locally. So when I tried all the following tried, I still get this error:

`ValueError: vllm-mistral--garrulus-- is not a valid BentoML tag: a tag's name or version must consist of alphanumeric characters, '_', '-', or '.', and must start and end with an alphanumeric character
`

command:

- `OPENLLM_USE_LOCAL_LATEST=True  HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1  openllm start mistral --model-id mistral/garrulus/`

- `openllm start  mistral/garrulus/`

- ` openllm start mistral --model-id  mistral/garrulus/`

- `openllm start mistral/garrulus  --dtype float16  --device all`


### Logs

_No response_

### Environment

**bentoml env**

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.11
`python`: 3.11.7
`platform`: Linux-5.10.0-27-cloud-amd64-x86_64-with-glibc2.31
`uid_gid`: 0:0
`conda`: 23.11.0
`in_conda_env`: True
<details><summary><code>conda_packages</code></summary>

<br>

```yaml
name: openllm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgomp=13.2.0=h807b86a_5
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.44.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=h59595ed_2
  - openssl=3.2.1=hd590300_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.11.7=hab00c5b_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - accelerate==0.26.1
      - aiohttp==3.9.3
      - aioprometheus==23.12.0
      - aiosignal==1.3.1
      - anyio==4.2.0
      - appdirs==1.4.4
      - asgiref==3.7.2
      - attrs==23.2.0
      - bentoml==1.1.11
      - bitsandbytes==0.41.3.post2
      - build==0.10.0
      - cattrs==23.1.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - circus==0.18.0
      - click==8.1.7
      - click-option-group==0.5.6
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - cuda-python==12.3.0
      - dataclasses-json==0.6.4
      - datasets==2.16.1
      - deepmerge==1.1.1
      - deprecated==1.2.14
      - dill==0.3.7
      - distlib==0.3.8
      - distro==1.9.0
      - einops==0.7.0
      - fastapi==0.109.2
      - fastcore==1.5.29
      - filelock==3.13.1
      - filetype==1.2.0
      - frozenlist==1.4.1
      - fs==2.4.16
      - fsspec==2023.10.0
      - ghapi==1.0.4
      - greenlet==3.0.3
      - grpcio==1.60.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - idna==3.6
      - importlib-metadata==6.11.0
      - inflection==0.5.1
      - jinja2==3.1.3
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - langchain==0.1.5
      - langchain-community==0.0.19
      - langchain-core==0.1.21
      - langsmith==0.0.87
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.20.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.5
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==11.525.150
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.11.1
      - openllm==0.4.44
      - openllm-client==0.4.44
      - openllm-core==0.4.44
      - opentelemetry-api==1.20.0
      - opentelemetry-instrumentation==0.41b0
      - opentelemetry-instrumentation-aiohttp-client==0.41b0
      - opentelemetry-instrumentation-asgi==0.41b0
      - opentelemetry-sdk==1.20.0
      - opentelemetry-semantic-conventions==0.41b0
      - opentelemetry-util-http==0.41b0
      - optimum==1.16.2
      - orjson==3.9.13
      - packaging==23.2
      - pandas==2.2.0
      - pathspec==0.12.1
      - pillow==10.2.0
      - pip-requirements-parser==32.0.1
      - pip-tools==7.3.0
      - platformdirs==4.2.0
      - prometheus-client==0.19.0
      - protobuf==4.25.2
      - psutil==5.9.8
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pydantic==1.10.13
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - quantile-python==1.1
      - ray==2.6.0
      - referencing==0.33.0
      - regex==2023.12.25
      - requests==2.31.0
      - rich==13.7.0
      - rpds-py==0.17.1
      - safetensors==0.4.2
      - schema==0.7.5
      - scipy==1.12.0
      - sentencepiece==0.1.99
      - simple-di==0.1.5
      - six==1.16.0
      - sniffio==1.3.0
      - sqlalchemy==2.0.25
      - starlette==0.36.3
      - sympy==1.12
      - tenacity==8.2.3
      - tokenizers==0.15.1
      - torch==2.1.2
      - tornado==6.4
      - tqdm==4.66.1
      - transformers==4.37.2
      - triton==2.1.0
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - urllib3==2.2.0
      - uvicorn==0.27.0.post1
      - uvloop==0.19.0
      - virtualenv==20.25.0
      - vllm==0.2.7
      - watchfiles==0.21.0
      - websockets==12.0
      - wrapt==1.16.0
      - xformers==0.0.23.post1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /opt/conda/envs/openllm-env
```

</details>

<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.26.1
aiohttp==3.9.3
aioprometheus==23.12.0
aiosignal==1.3.1
anyio==4.2.0
appdirs==1.4.4
asgiref==3.7.2
attrs==23.2.0
bentoml==1.1.11
bitsandbytes==0.41.3.post2
build==0.10.0
cattrs==23.1.2
certifi==2024.2.2
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
coloredlogs==15.0.1
contextlib2==21.6.0
cuda-python==12.3.0
dataclasses-json==0.6.4
datasets==2.16.1
deepmerge==1.1.1
Deprecated==1.2.14
dill==0.3.7
distlib==0.3.8
distro==1.9.0
einops==0.7.0
fastapi==0.109.2
fastcore==1.5.29
filelock==3.13.1
filetype==1.2.0
frozenlist==1.4.1
fs==2.4.16
fsspec==2023.10.0
ghapi==1.0.4
greenlet==3.0.3
grpcio==1.60.1
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.26.0
huggingface-hub==0.20.3
humanfriendly==10.0
idna==3.6
importlib-metadata==6.11.0
inflection==0.5.1
Jinja2==3.1.3
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
langchain==0.1.5
langchain-community==0.0.19
langchain-core==0.1.21
langsmith==0.0.87
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.20.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.5
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.2.1
ninja==1.11.1.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
openai==1.11.1
openllm==0.4.44
openllm-client==0.4.44
openllm-core==0.4.44
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.16.2
orjson==3.9.13
packaging==23.2
pandas==2.2.0
pathspec==0.12.1
pillow==10.2.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
platformdirs==4.2.0
prometheus-client==0.19.0
protobuf==4.25.2
psutil==5.9.8
pyarrow==15.0.0
pyarrow-hotfix==0.6
pydantic==1.10.13
Pygments==2.17.2
pyparsing==3.1.1
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-dotenv==1.0.1
python-json-logger==2.0.7
python-multipart==0.0.7
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
quantile-python==1.1
ray==2.6.0
referencing==0.33.0
regex==2023.12.25
requests==2.31.0
rich==13.7.0
rpds-py==0.17.1
safetensors==0.4.2
schema==0.7.5
scipy==1.12.0
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.25
starlette==0.36.3
sympy==1.12
tenacity==8.2.3
tokenizers==0.15.1
torch==2.1.2
tornado==6.4
tqdm==4.66.1
transformers==4.37.2
triton==2.1.0
typing-inspect==0.9.0
typing_extensions==4.9.0
tzdata==2023.4
urllib3==2.2.0
uvicorn==0.27.0.post1
uvloop==0.19.0
virtualenv==20.25.0
vllm==0.2.7
watchfiles==0.21.0
websockets==12.0
wrapt==1.16.0
xformers==0.0.23.post1
xxhash==3.4.1
yarl==1.9.4
zipp==3.17.0
```

</details>




**transformers-cli env**
````
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.37.2
- Platform: Linux-5.10.0-27-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.11.7
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.26.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

````

### System information (Optional)

_No response_

**Comment by bojiang** [comment]
close for openllm 0.6
